import { MaterialCommunityIcons } from '@expo/vector-icons';
import { collection, doc, onSnapshot, serverTimestamp, updateDoc } from 'firebase/firestore';
import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, ScrollView, TextInput } from 'react-native';
import styled from 'styled-components/native';

import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';
import { firestore } from '../../services/firebaseConfig';

const Bar = styled.View`padding: 14px 18px 6px;`; const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`; const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`; const ChipText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`; const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.card};`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`; const Row = styled.View`flex-direction: row; align-items: center;`; const Info = styled.View`flex: 1; margin-left: 12px;`; const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`; const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`; const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px;`; const DetailCard = styled(PortalCard)`margin: 18px;`; const Label = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; font-weight: 800; margin-top: 14px;`; const Value = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; line-height: 22px; margin-top: 4px;`; const Input = styled(TextInput)`min-height: 90px; margin-top: 10px; padding: 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt}; text-align-vertical: top;`; const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary};`; const ActionText = styled.Text`color: #fff; font-weight: 900;`; const MessageRow = styled.View`padding: 12px 0; border-bottom-width: 1px; border-bottom-color: ${({ theme }) => theme.portal.border};`;
const STATUSES = ['Todas', 'Recebida', 'Em Análise', 'Agendamento Liberado', 'Agendado', 'Concluída', 'Cancelada']; const date = value => value?.toDate ? value.toDate().toLocaleString('pt-BR') : value ? new Date(value).toLocaleString('pt-BR') : 'Não informado'; const messagesOf = item => Array.isArray(item.messages) ? item.messages : Object.entries(item.messages || {}).map(([id, message]) => ({ id, ...message }));

export default function AdminMicroempreendedorScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules(); const [items, setItems] = useState([]); const [filter, setFilter] = useState('Todas'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState(null); const [tab, setTab] = useState('dados'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!canUseAdminApp('microempreendedor')) return undefined; return onSnapshot(collection(firestore, 'assessoria-microempreendedor'), snapshot => setItems(snapshot.docs.map(row => ({ id: row.id, ...row.data() })))); }, [canUseAdminApp]);
  const visible = useMemo(() => items.filter(item => { const text = `${item.dadosUsuario?.name || ''} ${item.dadosUsuario?.email || ''} ${item.dadosUsuario?.cpf || ''} ${item.dadosAssessoria?.tipo || ''} ${item.dadosAssessoria?.nomeNegocio || ''}`.toLowerCase(); return (filter === 'Todas' || item.status === filter) && (!search.trim() || text.includes(search.toLowerCase().trim())); }).sort((a, b) => (b.dataSolicitacao?.toMillis?.() || 0) - (a.dataSolicitacao?.toMillis?.() || 0)), [items, filter, search]);
  if (!canUseAdminApp('microempreendedor')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  const update = async updates => { if (!selected) return; setBusy(true); try { await updateDoc(doc(firestore, 'assessoria-microempreendedor', selected.id), { ...updates, ultimaAtualizacao: serverTimestamp() }); setSelected(current => ({ ...current, ...updates })); setItems(current => current.map(item => item.id === selected.id ? { ...item, ...updates } : item)); } catch (error) { Alert.alert('Erro', error.message || 'Não foi possível atualizar a solicitação.'); } finally { setBusy(false); } };
  const sendMessage = () => { if (!message.trim()) return; const id = `admin-${Date.now()}`; update({ [`messages.${id}`]: { text: message.trim(), sender: 'admin', timestamp: new Date().toISOString(), readByAdmin: true, readByUser: false } }); setMessage(''); };
  if (selected) return <PortalBackground><PortalScreenHeader navigation={{ goBack: () => setSelected(null) }} eyebrow="Área administrativa" title="Microempreendedor" subtitle={selected.protocolo || selected.id} /><Horizontal style={{ paddingHorizontal: 18, paddingTop: 14 }}><Chip active={tab === 'dados'} onPress={() => setTab('dados')}><ChipText active={tab === 'dados'}>Dados</ChipText></Chip><Chip active={tab === 'situacao'} onPress={() => setTab('situacao')}><ChipText active={tab === 'situacao'}>Situação</ChipText></Chip><Chip active={tab === 'agendamento'} onPress={() => setTab('agendamento')}><ChipText active={tab === 'agendamento'}>Agendamento</ChipText></Chip><Chip active={tab === 'chat'} onPress={() => setTab('chat')}><ChipText active={tab === 'chat'}>Chat</ChipText></Chip></Horizontal><DetailCard>
    {tab === 'dados' && <><Label>Solicitante</Label><Value>{selected.dadosUsuario?.name || 'Não informado'}</Value><Label>Negócio</Label><Value>{selected.dadosAssessoria?.nomeNegocio || 'Não informado'}</Value><Label>Tipo de assessoria</Label><Value>{selected.dadosAssessoria?.tipo || 'Não informado'}</Value><Label>CNPJ</Label><Value>{selected.dadosAssessoria?.cnpj || 'Não informado'}</Value><Label>Descrição</Label><Value>{selected.dadosAssessoria?.descricao || 'Não informada'}</Value><Label>Solicitado em</Label><Value>{date(selected.dataSolicitacao)}</Value></>}
    {tab === 'situacao' && <><Label>Status atual</Label><Value>{selected.status || 'Não classificado'}</Value><Horizontal>{STATUSES.slice(1).map(status => <Chip key={status} active={selected.status === status} onPress={() => update({ status })}><ChipText active={selected.status === status}>{status}</ChipText></Chip>)}</Horizontal></>}
    {tab === 'agendamento' && <><Label>Data</Label><Value>{selected.appointmentDate || 'Não agendado'}</Value><Label>Horário</Label><Value>{selected.appointmentTime || 'Não informado'}</Value><Detail>Os horários devem ser configurados pelo controle de disponibilidade do portal.</Detail></>}
    {tab === 'chat' && <>{messagesOf(selected).map((item, index) => <MessageRow key={item.id || index}><Value>{item.text || item.message || ''}</Value><Label>{item.sender || 'Atendimento'}</Label></MessageRow>)}{!messagesOf(selected).length && <Value>Nenhuma mensagem registrada.</Value>}<Input multiline value={message} onChangeText={setMessage} placeholder="Digite uma mensagem para o empreendedor..." placeholderTextColor="#94a3b8" /><Action disabled={busy || !message.trim()} onPress={sendMessage}><ActionText>{busy ? 'Enviando...' : 'Enviar mensagem'}</ActionText></Action></>}
  </DetailCard></PortalBackground>;
  return <PortalBackground><PortalScreenHeader navigation={navigation} eyebrow="Área administrativa" title="Microempreendedor" subtitle="Gerencie orientações para MEI, finanças, impostos e negócios." /><Bar><Horizontal>{STATUSES.map(status => <Chip key={status} active={filter === status} onPress={() => setFilter(status)}><ChipText active={filter === status}>{status}</ChipText></Chip>)}</Horizontal><Search value={search} onChangeText={setSearch} placeholder="Buscar nome, CPF, negócio ou tipo" placeholderTextColor="#94a3b8" /></Bar><FlatList data={visible} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 36 }} ListEmptyComponent={<Empty>Nenhuma solicitação encontrada.</Empty>} renderItem={({ item }) => <Card onPress={() => { setSelected(item); setTab('dados'); }}><Row><MaterialCommunityIcons name="briefcase-outline" size={29} color="#059669" /><Info><Title>{item.dadosAssessoria?.tipo || 'Assessoria ao Microempreendedor'}</Title><Detail>{item.dadosUsuario?.name || 'Solicitante não informado'} · {item.dadosAssessoria?.nomeNegocio || 'Negócio não informado'}</Detail><Detail>{item.status || 'Não classificado'} · {date(item.dataSolicitacao)}</Detail></Info><MaterialCommunityIcons name="chevron-right" size={22} color="#94a3b8" /></Row></Card>} />
  </PortalBackground>;
}
