import { MaterialCommunityIcons } from '@expo/vector-icons';
import { collection, doc, onSnapshot, serverTimestamp, updateDoc } from 'firebase/firestore';
import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, ScrollView, TextInput } from 'react-native';
import styled from 'styled-components/native';
import { firestore } from '../../services/firebaseConfig';
import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';

const STATUS = ['Todos', 'Em Análise', 'Pendente', 'Finalizada', 'Em Negociação', 'Documentação Reprovada', 'Documentação Reenviada'];
const dateOf = item => item.createdAt?.toDate ? item.createdAt.toDate() : item.dataSolicitacao?.toDate ? item.dataSolicitacao.toDate() : new Date(item.createdAt || item.dataSolicitacao || 0);
const dateLabel = item => { const value = dateOf(item); return Number.isNaN(value.getTime()) ? 'Data não informada' : value.toLocaleString('pt-BR'); };
const normalize = value => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const messagesOf = value => Array.isArray(value) ? value : Object.entries(value || {}).map(([id, message]) => ({ id, ...message }));
const FilterBar = styled.View`padding: 14px 18px 6px;`;
const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`;
const ChipText = styled.Text`font-size: 12px; font-weight: 800; color: ${({ active, theme }) => active ? '#fff' : theme.portal.text};`;
const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; background-color: ${({ theme }) => theme.portal.card}; color: ${({ theme }) => theme.portal.text}; font-size: 12px;`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`;
const Row = styled.View`flex-direction: row; align-items: center;`;
const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`;
const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`;
const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px; line-height: 22px;`;
const DetailCard = styled(PortalCard)`margin: 18px;`;
const Label = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; font-weight: 800; margin-top: 14px;`;
const Value = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; line-height: 22px; margin-top: 4px;`;
const Tabs = styled.View`flex-direction: row; flex-wrap: wrap; padding: 14px 18px 0;`;
const Tab = styled.TouchableOpacity`padding: 10px 12px; margin: 0 7px 8px 0; border-radius: 10px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card};`;
const TabText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 900;`;
const StatusButton = styled.TouchableOpacity`padding: 10px 12px; border-radius: 10px; margin: 8px 7px 0 0; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.pageAlt};`;
const StatusText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const MessageInput = styled(TextInput)`min-height: 90px; margin-top: 10px; padding: 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt}; text-align-vertical: top;`;
const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary}; opacity: ${({ disabled }) => disabled ? .55 : 1};`;
const ActionText = styled.Text`color: #fff; font-weight: 900;`;

export default function AdminProconScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules();
  const [items, setItems] = useState([]); const [filter, setFilter] = useState('Todos'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState(null); const [tab, setTab] = useState('dados'); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!canUseAdminApp('procon')) return undefined; return onSnapshot(collection(firestore, 'procon-atendimentos'), snap => setItems(snap.docs.map(row => ({ id: row.id, ...row.data() })))); }, [canUseAdminApp]);
  const visible = useMemo(() => items.filter(item => { const text = normalize(`${item.nome || ''} ${item.dadosUsuario?.name || ''} ${item.cpf || ''} ${item.assunto || ''} ${item.descricao || ''} ${item.id}`); return (filter === 'Todos' || normalize(item.status || item.situacao || 'Em Análise') === normalize(filter)) && (!search.trim() || text.includes(normalize(search))); }).sort((a, b) => dateOf(b) - dateOf(a)), [filter, items, search]);
  if (!canUseAdminApp('procon')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  const update = async updates => { if (!selected) return; setSaving(true); try { await updateDoc(doc(firestore, 'procon-atendimentos', selected.id), { ...updates, updatedAt: serverTimestamp() }); setSelected(current => ({ ...current, ...updates })); setItems(current => current.map(item => item.id === selected.id ? { ...item, ...updates } : item)); } catch (error) { Alert.alert('Erro', error.message || 'Não foi possível atualizar o atendimento.'); } finally { setSaving(false); } };
  if (selected) return <PortalBackground><PortalScreenHeader navigation={{ goBack: () => setSelected(null) }} eyebrow="Área administrativa" title="PROCON" subtitle={selected.protocolo || selected.id} /><Tabs>{[['dados', 'Dados'], ['situacao', 'Situação'], ['arquivos', 'Arquivos'], ['chat', 'Chat']].map(([id, label]) => <Tab key={id} active={tab === id} onPress={() => setTab(id)}><TabText active={tab === id}>{label}</TabText></Tab>)}</Tabs><DetailCard>{tab === 'dados' && <><Label>Consumidor</Label><Value>{selected.nome || selected.dadosUsuario?.name || 'Não informado'}</Value><Label>CPF</Label><Value>{selected.cpf || selected.dadosUsuario?.cpf || 'Não informado'}</Value><Label>Fornecedor</Label><Value>{selected.fornecedor || selected.empresa || 'Não informado'}</Value><Label>Assunto</Label><Value>{selected.assunto || selected.titulo || 'Reclamação de consumidor'}</Value><Label>Descrição</Label><Value>{selected.descricao || selected.relato || 'Não informado'}</Value></>}{tab === 'situacao' && <><Label>Status atual</Label><Value>{selected.status || selected.situacao || 'Em Análise'}</Value>{STATUS.slice(1).map(value => <StatusButton key={value} active={(selected.status || selected.situacao) === value} disabled={saving} onPress={() => update({ status: value })}><StatusText active={(selected.status || selected.situacao) === value}>{value}</StatusText></StatusButton>)}</>}{tab === 'arquivos' && <><Label>Arquivos anexados</Label><Value>{selected.anexos || selected.arquivos ? 'Arquivos disponíveis no atendimento.' : 'Nenhum arquivo anexado.'}</Value></>}{tab === 'chat' && <>{messagesOf(selected.messages).map((item, index) => <Value key={item.id || index}>{item.text || item.message || ''}</Value>)}{!messagesOf(selected.messages).length && <Value>Nenhuma mensagem registrada.</Value>}<MessageInput multiline value={message} onChangeText={setMessage} placeholder="Digite uma mensagem para o consumidor..." placeholderTextColor="#94a3b8" /><Action disabled={saving || !message.trim()} onPress={() => { const id = `admin-${Date.now()}`; update({ [`messages.${id}`]: { text: message.trim(), sender: 'admin', timestamp: new Date().toISOString(), readByAdmin: true, readByUser: false } }); setMessage(''); }}><ActionText>{saving ? 'Enviando...' : 'Enviar mensagem'}</ActionText></Action></>}</DetailCard></PortalBackground>;
  return <PortalBackground><PortalScreenHeader navigation={navigation} eyebrow="Área administrativa" title="PROCON" subtitle="Gerencie atendimentos, consumidores e fornecedores." /><FilterBar><Horizontal>{STATUS.map(value => <Chip key={value} active={filter === value} onPress={() => setFilter(value)}><ChipText active={filter === value}>{value}</ChipText></Chip>)}</Horizontal><Search value={search} onChangeText={setSearch} placeholder="Buscar consumidor, fornecedor, assunto ou protocolo" placeholderTextColor="#94a3b8" /></FilterBar><FlatList data={visible} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 36 }} ListEmptyComponent={<Empty>Nenhum atendimento encontrado para este filtro.</Empty>} renderItem={({ item }) => <Card onPress={() => { setSelected(item); setTab('dados'); }}><Row><MaterialCommunityIcons name="shield-check-outline" size={29} color="#2563eb" /><Info><Title>{item.assunto || item.titulo || 'Atendimento PROCON'}</Title><Detail>Consumidor: {item.nome || item.dadosUsuario?.name || 'Não informado'}</Detail><Detail>{item.fornecedor || item.empresa || 'Fornecedor não informado'} · {item.status || item.situacao || 'Em Análise'}</Detail><Detail>{dateLabel(item)}</Detail></Info><MaterialCommunityIcons name="chevron-right" size={22} color="#94a3b8" /></Row></Card>} /></PortalBackground>;
}
