import { MaterialCommunityIcons } from '@expo/vector-icons';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import { Fragment, useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, ScrollView, TextInput } from 'react-native';
import styled from 'styled-components/native';

import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';
import { runAdministrativeCommand } from '../../services/AdministrativeCommand';
import { firestore } from '../../services/firebaseConfig';

const Bar = styled.View`padding: 14px 18px 6px;`; const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`; const ChipText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.card};`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`; const Row = styled.View`flex-direction: row; align-items: center;`; const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`; const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`; const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px;`;
const FormCard = styled(PortalCard)`margin: 18px;`; const Label = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 13px; font-weight: 800; margin-top: 12px;`; const Input = styled(TextInput)`min-height: 44px; margin-top: 7px; padding: 0 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt};`; const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary};`; const ActionText = styled.Text`color: #fff; font-weight: 900;`;
const useRows = name => { const [rows, setRows] = useState([]); useEffect(() => onSnapshot(query(collection(firestore, name), orderBy('createdAt', 'desc')), snap => setRows(snap.docs.map(row => ({ id: row.id, ...row.data() }))), () => setRows([])), [name]); return rows; }; const date = value => value?.toDate ? value.toDate().toLocaleDateString('pt-BR') : value ? new Date(value).toLocaleDateString('pt-BR') : 'Não informado'; const money = value => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

export default function AdminFrotasScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules(); const vehicles = useRows('fleetVehicles'); const drivers = useRows('fleetDrivers'); const fuelings = useRows('fleetFuelings'); const maintenance = useRows('fleetMaintenance'); const incidents = useRows('fleetIncidents');
  const [section, setSection] = useState('resumo'); const [search, setSearch] = useState(''); const [vehicle, setVehicle] = useState({ plate: '', description: '', brand: '', model: '', year: '', fuelType: '', currentMileage: '', departmentName: '', registrationExpiresAt: '', insuranceExpiresAt: '', inspectionDueAt: '' }); const [driver, setDriver] = useState({ name: '', licenseNumber: '', licenseCategory: '', licenseExpiresAt: '' }); const [event, setEvent] = useState({ vehicleId: '', kind: 'fueling', occurredAt: '', mileage: '', quantity: '', amount: '', supplierName: '', description: '' }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const run = async (action, payload, success) => { setBusy(true); setMessage(''); try { await runAdministrativeCommand('frotas', action, payload); setMessage(success); } catch (error) { setMessage(error.message || 'Não foi possível concluir a operação.'); } finally { setBusy(false); } }; const filteredVehicles = useMemo(() => vehicles.filter(item => `${item.plate} ${item.description} ${item.departmentName}`.toLowerCase().includes(search.toLowerCase())), [vehicles, search]);
  if (!canUseAdminApp('frotas')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  const createVehicle = () => { if (!vehicle.plate.trim() || !vehicle.description.trim()) return Alert.alert('Atenção', 'Informe placa e identificação.'); run('createVehicle', vehicle, 'Veículo cadastrado.'); setVehicle({ plate: '', description: '', brand: '', model: '', year: '', fuelType: '', currentMileage: '', departmentName: '', registrationExpiresAt: '', insuranceExpiresAt: '', inspectionDueAt: '' }); };
  const createDriver = () => { if (!driver.name.trim() || !driver.licenseNumber.trim()) return Alert.alert('Atenção', 'Informe nome e CNH.'); run('createDriver', driver, 'Condutor cadastrado.'); setDriver({ name: '', licenseNumber: '', licenseCategory: '', licenseExpiresAt: '' }); };
  const createEvent = () => { if (!event.vehicleId || !event.description.trim()) return Alert.alert('Atenção', 'Informe veículo e descrição.'); run('createEvent', event, 'Registro incluído.'); setEvent({ vehicleId: '', kind: 'fueling', occurredAt: '', mileage: '', quantity: '', amount: '', supplierName: '', description: '' }); };
  const allEvents = [...fuelings, ...maintenance, ...incidents].sort((a, b) => (b.createdAt?.toMillis?.() || 0) - (a.createdAt?.toMillis?.() || 0));
  return <PortalBackground><PortalScreenHeader navigation={navigation} eyebrow="Área administrativa" title="Gestão de Frotas" subtitle="Controle veículos, condutores, documentos, manutenção e custos." /><Bar><Horizontal>{[['resumo', 'Visão geral'], ['veiculos', 'Veículos'], ['condutores', 'Condutores'], ['registros', 'Registros'], ['novo', 'Novo veículo']].map(([id, label]) => <Chip key={id} active={section === id} onPress={() => setSection(id)}><ChipText active={section === id}>{label}</ChipText></Chip>)}</Horizontal>{['veiculos', 'registros'].includes(section) && <Search value={search} onChangeText={setSearch} placeholder="Buscar na frota" placeholderTextColor="#94a3b8" />}</Bar>{message ? <Detail style={{ marginHorizontal: 18 }}>{message}</Detail> : null}
    {section === 'resumo' && <ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 40 }}><FormCard><Title>Resumo da frota</Title><Detail>{vehicles.length} veículo(s) cadastrado(s)</Detail><Detail>{drivers.length} condutor(es)</Detail><Detail>{fuelings.length} abastecimento(s)</Detail><Detail>{maintenance.length} manutenção(ões)</Detail><Detail>{incidents.length} ocorrência(s)</Detail></FormCard><FormCard><Title>Vencimentos próximos</Title>{vehicles.filter(item => item.registrationExpiresAt || item.insuranceExpiresAt || item.inspectionDueAt).slice(0, 8).map(item => <Detail key={item.id}>{item.plate} · licenciamento {date(item.registrationExpiresAt)}</Detail>)}{!vehicles.length && <Detail>Nenhum veículo cadastrado.</Detail>}</FormCard></ScrollView>}
    {section === 'veiculos' && <FlatList data={filteredVehicles} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhum veículo encontrado.</Empty>} renderItem={({ item }) => <Card><Row><MaterialCommunityIcons name="car-outline" size={30} color="#2563eb" /><Info><Title>{item.plate} · {item.description}</Title><Detail>{item.brand || ''} {item.model || ''} · {item.departmentName || 'Setor não informado'}</Detail><Detail>{item.currentMileage || 0} km · Combustível: {item.fuelType || 'Não informado'}</Detail><Detail>Seguro: {date(item.insuranceExpiresAt)} · Revisão: {date(item.inspectionDueAt)}</Detail></Info></Row></Card>} />}
    {section === 'novo' && <FormCard><Title>Novo veículo</Title>{[['plate', 'Placa *'], ['description', 'Identificação *'], ['brand', 'Marca'], ['model', 'Modelo'], ['year', 'Ano'], ['fuelType', 'Combustível'], ['currentMileage', 'Quilometragem atual'], ['departmentName', 'Setor'], ['registrationExpiresAt', 'Licenciamento (AAAA-MM-DD)'], ['insuranceExpiresAt', 'Seguro (AAAA-MM-DD)'], ['inspectionDueAt', 'Próxima revisão (AAAA-MM-DD)']].map(([key, label]) => <Fragment key={key}><Label>{label}</Label><Input value={vehicle[key]} onChangeText={value => setVehicle({ ...vehicle, [key]: value })} placeholder={label} placeholderTextColor="#94a3b8" /></Fragment>)}<Action disabled={busy} onPress={createVehicle}><ActionText>Cadastrar veículo</ActionText></Action></FormCard>}
    {section === 'condutores' && <><FormCard><Title>Novo condutor</Title><Label>Nome *</Label><Input value={driver.name} onChangeText={name => setDriver({ ...driver, name })} placeholder="Nome completo" placeholderTextColor="#94a3b8" /><Label>CNH *</Label><Input value={driver.licenseNumber} onChangeText={licenseNumber => setDriver({ ...driver, licenseNumber })} placeholder="Número da CNH" placeholderTextColor="#94a3b8" /><Label>Categoria</Label><Input value={driver.licenseCategory} onChangeText={licenseCategory => setDriver({ ...driver, licenseCategory })} placeholder="Categoria" placeholderTextColor="#94a3b8" /><Label>Vencimento</Label><Input value={driver.licenseExpiresAt} onChangeText={licenseExpiresAt => setDriver({ ...driver, licenseExpiresAt })} placeholder="AAAA-MM-DD" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={createDriver}><ActionText>Cadastrar condutor</ActionText></Action></FormCard><FlatList data={drivers} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} renderItem={({ item }) => <Card><Title>{item.name}</Title><Detail>CNH {item.licenseNumber} · Categoria {item.licenseCategory || 'Não informada'}</Detail><Detail>Vencimento: {date(item.licenseExpiresAt)}</Detail></Card>} /></>}
    {section === 'registros' && <><FormCard><Title>Novo registro</Title><Label>Veículo (ID) *</Label><Input value={event.vehicleId} onChangeText={vehicleId => setEvent({ ...event, vehicleId })} placeholder="ID do veículo" placeholderTextColor="#94a3b8" /><Label>Tipo</Label><Horizontal>{[['fueling', 'Abastecimento'], ['maintenance', 'Manutenção'], ['incident', 'Ocorrência'], ['fine', 'Multa'], ['document', 'Documento']].map(([key, label]) => <Chip key={key} active={event.kind === key} onPress={() => setEvent({ ...event, kind: key })}><ChipText active={event.kind === key}>{label}</ChipText></Chip>)}</Horizontal><Label>Valor</Label><Input value={event.amount} onChangeText={amount => setEvent({ ...event, amount })} keyboardType="decimal-pad" placeholder="0,00" placeholderTextColor="#94a3b8" /><Label>Quilometragem</Label><Input value={event.mileage} onChangeText={mileage => setEvent({ ...event, mileage })} keyboardType="numeric" placeholder="0" placeholderTextColor="#94a3b8" /><Label>Descrição *</Label><Input multiline value={event.description} onChangeText={description => setEvent({ ...event, description })} placeholder="Descrição do registro" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={createEvent}><ActionText>Salvar registro</ActionText></Action></FormCard><FlatList data={allEvents.filter(item => `${item.plate} ${item.description} ${item.kind}`.toLowerCase().includes(search.toLowerCase()))} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhum registro encontrado.</Empty>} renderItem={({ item }) => <Card><Title>{item.plate || item.vehicleId} · {item.kind || 'Registro'}</Title><Detail>{item.description || 'Sem descrição'} · {money(item.amount)}</Detail><Detail>{date(item.occurredAt || item.createdAt)} · {item.mileage || 0} km</Detail></Card>} /></>}
  </PortalBackground>;
}
