import { MaterialCommunityIcons } from '@expo/vector-icons';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import { useEffect, useMemo, useState } from 'react';
import { FlatList, Linking, ScrollView } from 'react-native';
import styled from 'styled-components/native';

import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';
import { firestore } from '../../services/firebaseConfig';

const Bar = styled.View`padding: 14px 18px 6px;`;
const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`;
const ChipText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const SearchInput = styled.TextInput`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.card};`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`;
const Row = styled.View`flex-direction: row; align-items: center;`;
const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`;
const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`;
const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px;`;
const DetailCard = styled(PortalCard)`margin: 18px;`;
const Label = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; font-weight: 800; margin-top: 14px;`;
const Value = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; line-height: 22px; margin-top: 4px;`;
const Action = styled.TouchableOpacity`margin-top: 16px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary};`;
const ActionText = styled.Text`color: #fff; font-weight: 900;`;
const date = value => value?.toDate ? value.toDate().toLocaleDateString('pt-BR') : value ? new Date(value).toLocaleDateString('pt-BR') : 'Não informado';
const useRows = name => { const [rows, setRows] = useState([]); useEffect(() => onSnapshot(query(collection(firestore, name), orderBy('createdAt', 'desc')), snap => setRows(snap.docs.map(row => ({ id: row.id, ...row.data() }))), () => setRows([])), [name]); return rows; };

export default function AdminLegislativoScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules();
  const matters = useRows('legislativeMatters'); const sessions = useRows('legislativeSessions'); const committees = useRows('legislativeCommittees');
  const [section, setSection] = useState('materias'); const [selected, setSelected] = useState(null);
  const [search, setSearch] = useState('');
  const visibleMatters = useMemo(() => matters.filter(item => `${item.title} ${item.ementa} ${item.identifier} ${item.authorName}`.toLowerCase().includes(search.toLowerCase())), [matters, search]);
  if (!canUseAdminApp('legislativo')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  if (selected) return <PortalBackground><PortalScreenHeader navigation={{ goBack: () => setSelected(null) }} eyebrow="Gestão Legislativa" title={selected.kind === 'matter' ? 'Detalhes da matéria' : selected.kind === 'session' ? 'Detalhes da sessão' : 'Detalhes da comissão'} subtitle={selected.title || selected.name || selected.identifier} /><ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 40 }}><DetailCard><Title>{selected.title || selected.name || selected.identifier || 'Registro legislativo'}</Title><Label>Tipo / situação</Label><Value>{selected.type || selected.status || 'Não informado'}</Value>{selected.ementa ? <><Label>Ementa</Label><Value>{selected.ementa}</Value></> : null}{selected.description ? <><Label>Descrição</Label><Value>{selected.description}</Value></> : null}{selected.authorName ? <><Label>Autor</Label><Value>{selected.authorName}</Value></> : null}{selected.date || selected.startsAt ? <><Label>Data</Label><Value>{date(selected.date || selected.startsAt)}</Value></> : null}{selected.location ? <><Label>Local</Label><Value>{selected.location}</Value></> : null}{selected.onlineUrl || selected.meetingUrl || selected.streamUrl ? <Action onPress={() => Linking.openURL(selected.onlineUrl || selected.meetingUrl || selected.streamUrl)}><ActionText>Participar online</ActionText></Action> : null}</DetailCard></ScrollView></PortalBackground>;
  return <PortalBackground><PortalScreenHeader navigation={navigation} eyebrow="Área administrativa" title="Gestão Legislativa" subtitle="Matérias, sessões e comissões do vereador." /><Bar><Horizontal>{[['materias', 'Minhas matérias'], ['sessoes', 'Sessões'], ['comissoes', 'Comissões']].map(([id, label]) => <Chip key={id} active={section === id} onPress={() => { setSection(id); setSearch(''); }}><ChipText active={section === id}>{label}</ChipText></Chip>)}</Horizontal>{section === 'materias' ? <SearchInput value={search} onChangeText={setSearch} placeholder="Buscar matéria, ementa ou autor" placeholderTextColor="#94a3b8" /> : null}</Bar>{section === 'materias' && <FlatList data={visibleMatters} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhuma matéria encontrada.</Empty>} renderItem={({ item }) => <Card onPress={() => setSelected({ ...item, kind: 'matter' })}><Row><MaterialCommunityIcons name="file-document-edit-outline" size={28} color="#0284C7" /><Info><Title>{item.identifier || item.title || 'Matéria sem identificação'}</Title><Detail>{item.ementa || item.description || 'Ementa não informada'}</Detail><Detail>{item.status || 'Em tramitação'} · {date(item.createdAt)}</Detail></Info><MaterialCommunityIcons name="chevron-right" size={22} color="#94a3b8" /></Row></Card>} />}{section === 'sessoes' && <FlatList data={sessions} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhuma sessão encontrada.</Empty>} renderItem={({ item }) => <Card onPress={() => setSelected({ ...item, kind: 'session' })}><Row><MaterialCommunityIcons name="calendar-clock" size={28} color="#0f766e" /><Info><Title>{item.title || item.name || 'Sessão legislativa'}</Title><Detail>{date(item.startsAt || item.date)} · {item.status || 'Agendada'}</Detail><Detail>{item.location || (item.onlineUrl || item.meetingUrl ? 'Participação online disponível' : 'Local não informado')}</Detail></Info><MaterialCommunityIcons name="chevron-right" size={22} color="#94a3b8" /></Row></Card>} />}{section === 'comissoes' && <FlatList data={committees} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhuma comissão encontrada.</Empty>} renderItem={({ item }) => <Card onPress={() => setSelected({ ...item, kind: 'committee' })}><Row><MaterialCommunityIcons name="account-group-outline" size={28} color="#7c3aed" /><Info><Title>{item.name || item.title || 'Comissão'}</Title><Detail>{item.description || 'Comissão legislativa'}</Detail><Detail>{item.meetingDate ? `Próxima reunião: ${date(item.meetingDate)}` : item.onlineUrl || item.meetingUrl ? 'Reunião online disponível' : 'Sem reunião agendada'}</Detail></Info><MaterialCommunityIcons name="chevron-right" size={22} color="#94a3b8" /></Row></Card>} />}</PortalBackground>;
}
