import { MaterialCommunityIcons } from '@expo/vector-icons';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as ImagePicker from 'expo-image-picker';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import { Fragment, useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, Modal, ScrollView, TextInput, TouchableOpacity } from 'react-native';
import styled from 'styled-components/native';

import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';
import { runAdministrativeCommand } from '../../services/AdministrativeCommand';
import { firestore } from '../../services/firebaseConfig';
import { uploadFileToStorage } from '../../services/storageService';

const Bar = styled.View`padding: 14px 18px 6px;`;
const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`;
const ChipText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.card};`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`;
const Row = styled.View`flex-direction: row; align-items: center;`;
const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`;
const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`;
const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px;`;
const FormCard = styled(PortalCard)`margin: 18px;`;
const Label = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 13px; font-weight: 800; margin-top: 12px;`;
const Input = styled(TextInput)`height: 44px; margin-top: 7px; padding: 0 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt};`;
const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary};`;
const ActionText = styled.Text`color: #fff; font-weight: 900;`;
const FloatingAction = styled.TouchableOpacity`position: absolute; right: 22px; bottom: 26px; width: 56px; height: 56px; border-radius: 28px; align-items: center; justify-content: center; background-color: ${({ theme }) => theme.portal.primary}; elevation: 6; shadow-color: #000; shadow-opacity: .22; shadow-radius: 7px; shadow-offset: 0px 4px;`;
const ScanButton = styled.TouchableOpacity`flex-direction: row; align-items: center; justify-content: center; margin-top: 12px; padding: 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.primary}; background-color: ${({ theme }) => `${theme.portal.primary}16`};`;
const ScanButtonText = styled.Text`margin-left: 8px; color: ${({ theme }) => theme.portal.primary}; font-weight: 900;`;
const ScannerOverlay = styled.View`position: absolute; top: 0; right: 0; bottom: 0; left: 0; justify-content: flex-end; background-color: rgba(0,0,0,.25);`;
const ScannerSheet = styled.View`padding: 20px; background-color: ${({ theme }) => theme.portal.card}; border-top-left-radius: 22px; border-top-right-radius: 22px;`;
const ImagePreview = styled.Image`width: 100%; height: 150px; margin-top: 12px; border-radius: 10px;`;
const DashboardGrid = styled.View`flex-direction: row; flex-wrap: wrap; justify-content: space-between;`;
const MetricCard = styled(PortalCard)`width: 48%; margin: 0 0 10px; padding: 14px;`;
const MetricLabel = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 11px; font-weight: 700; margin-top: 8px;`;
const MetricValue = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 23px; font-weight: 900; margin-top: 3px;`;
const DashboardCard = styled(PortalCard)`margin: 0 0 12px; padding: 16px;`;
const SectionTitle = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 16px; font-weight: 900; margin-bottom: 12px;`;
const ChartRow = styled.View`flex-direction: row; align-items: center; margin-top: 9px;`;
const ChartLabel = styled.Text`width: 106px; color: ${({ theme }) => theme.portal.muted}; font-size: 11px;`;
const ChartTrack = styled.View`flex: 1; height: 9px; border-radius: 5px; background-color: ${({ theme }) => theme.portal.pageAlt}; overflow: hidden;`;
const ChartBar = styled.View`height: 100%; border-radius: 5px; background-color: ${({ theme }) => theme.portal.primary}; width: ${({ width }) => `${width}%`};`;
const ChartCount = styled.Text`width: 28px; margin-left: 7px; color: ${({ theme }) => theme.portal.text}; font-size: 11px; font-weight: 800; text-align: right;`;
const STATUS = { active: 'Em uso', maintenance: 'Em manutenção', loaned: 'Emprestado', written_off: 'Baixado' };
const CONSERVATION = { good: 'Bom', regular: 'Regular', poor: 'Ruim' };
const date = value => value?.toDate ? value.toDate().toLocaleDateString('pt-BR') : value ? new Date(value).toLocaleDateString('pt-BR') : 'Não informado';
const useRows = name => { const [rows, setRows] = useState([]); useEffect(() => onSnapshot(query(collection(firestore, name), orderBy('createdAt', 'desc')), snap => setRows(snap.docs.map(row => ({ id: row.id, ...row.data() }))), () => setRows([])), [name]); return rows; };

export default function AdminPatrimonioScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules(); const assets = useRows('assets'); const movements = useRows('assetMovements'); const inventories = useRows('assetInventories');
  const [section, setSection] = useState('resumo'); const [search, setSearch] = useState(''); const [form, setForm] = useState({ tombNumber: '', description: '', category: '', departmentName: '', location: '', responsibleName: '', conservationState: 'good', acquisitionValue: '' }); const [move, setMove] = useState({ assetId: '', type: 'transfer', departmentName: '', location: '', responsibleName: '', reason: '' }); const [inventoryName, setInventoryName] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [selectedAsset, setSelectedAsset] = useState(null); const [scannerVisible, setScannerVisible] = useState(false); const [scanTarget, setScanTarget] = useState('form'); const [permission, requestPermission] = useCameraPermissions();
  const run = async (action, payload, success) => { setBusy(true); setMessage(''); try { await runAdministrativeCommand('patrimonio', action, payload); setMessage(success); } catch (error) { setMessage(error.message || 'Não foi possível concluir a operação.'); } finally { setBusy(false); } };
  const filtered = useMemo(() => assets.filter(item => `${item.tombNumber} ${item.description} ${item.category} ${item.departmentName}`.toLowerCase().includes(search.toLowerCase())), [assets, search]);
  const statusSummary = useMemo(() => Object.entries(STATUS).map(([key, label]) => ({ label, count: assets.filter(item => item.status === key).length })), [assets]);
  const categorySummary = useMemo(() => Object.entries(assets.reduce((result, item) => { const key = item.category || 'Sem categoria'; result[key] = (result[key] || 0) + 1; return result; }, {})).sort((a, b) => b[1] - a[1]).slice(0, 5), [assets]);
  const maxStatus = Math.max(1, ...statusSummary.map(item => item.count));
  const headerNavigation = { ...navigation, goBack: () => section === 'novo' ? setSection('bens') : section === 'novo-movimento' ? setSection('movimentos') : navigation.goBack() };
  if (!canUseAdminApp('patrimonio')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  const chooseAssetImage = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.85 }); if (result.canceled) return; try { const imageUri = result.assets[0].uri; const imageUrl = await uploadFileToStorage(imageUri, `patrimonio/imagens/${form.tombNumber || Date.now()}`); setForm(current => ({ ...current, imageUri, imageUrl })); } catch (error) { Alert.alert('Erro', error.message || 'Não foi possível anexar a imagem.'); } };
  const openScanner = async target => { if (!permission?.granted) { const result = await requestPermission(); if (!result.granted) return Alert.alert('Permissão necessária', 'Permita o acesso à câmera para ler o código do bem.'); } setScanTarget(target); setScannerVisible(true); };
  const handleScan = ({ data }) => { if (!data) return; setScannerVisible(false); const code = String(data).trim(); const existing = assets.find(item => String(item.id || '') === code || String(item.tombNumber || item.barcode || item.qrCode || '').trim() === code); if (scanTarget === 'movement') { if (existing) { setMove(current => ({ ...current, assetId: existing.id })); setMessage(`Bem identificado: ${existing.tombNumber || existing.description}.`); } else { setMove(current => ({ ...current, assetId: '' })); Alert.alert('Bem não encontrado', 'O código lido não corresponde a um bem cadastrado. Informe um identificador válido manualmente.'); } return; } if (existing) { setSelectedAsset(existing); setSection('detalhe'); setMessage('Bem já cadastrado.'); return; } if (scanTarget === 'search') setSearch(code); else setForm(current => ({ ...current, tombNumber: code })); };
  const createAsset = async () => { if (!form.description.trim()) return Alert.alert('Atenção', 'Informe a descrição do bem.'); const identifier = form.tombNumber.trim() || `BEM-${Date.now()}`; const existing = assets.find(item => String(item.tombNumber || '').trim() === identifier); if (existing) { setSelectedAsset(existing); setSection('detalhe'); return Alert.alert('Bem já cadastrado', 'Este tombamento já está cadastrado.'); } setBusy(true); try { const qrUrl = `https://quickchart.io/qr?text=${encodeURIComponent(`patrimonio:${identifier}`)}&size=600`; const qrCodeUrl = await uploadFileToStorage(qrUrl, `patrimonio/${identifier}`, { contentType: 'image/png' }); await runAdministrativeCommand('patrimonio', 'createAsset', { ...form, tombNumber: identifier, qrCodeUrl }); setMessage('Bem patrimonial cadastrado e QR Code salvo.'); setForm({ tombNumber: '', description: '', category: '', departmentName: '', location: '', responsibleName: '', conservationState: 'good', acquisitionValue: '' }); setSection('bens'); } catch (error) { setMessage(error.message || 'Não foi possível cadastrar o bem.'); } finally { setBusy(false); } };
  const moveAsset = () => { const asset = assets.find(item => item.id === move.assetId || String(item.tombNumber || '').trim() === move.assetId.trim()); if (!asset || !move.reason.trim()) return Alert.alert('Bem não encontrado', 'Selecione ou informe um bem cadastrado antes de registrar a movimentação.'); run('moveAsset', { ...move, assetId: asset.id, assetIdentifier: asset.tombNumber || asset.identifier || '' }, 'Movimentação registrada.'); setMove({ assetId: '', type: 'transfer', departmentName: '', location: '', responsibleName: '', reason: '' }); };
  return <PortalBackground><PortalScreenHeader navigation={headerNavigation} eyebrow="Área administrativa" title="Patrimônio" subtitle="Controle bens, localização, responsabilidade e inventários." /><Bar><Horizontal>{[['resumo', 'Visão geral'], ['bens', 'Bens'], ['movimentos', 'Movimentações'], ['inventarios', 'Inventários']].map(([id, label]) => <Chip key={id} active={section === id} onPress={() => setSection(id)}><ChipText active={section === id}>{label}</ChipText></Chip>)}</Horizontal>{section === 'bens' && <><Search value={search} onChangeText={setSearch} placeholder="Buscar tombamento, bem ou setor" placeholderTextColor="#94a3b8" /><ScanButton onPress={() => openScanner('search')}><MaterialCommunityIcons name="barcode-scan" size={20} color="#0284C7" /><ScanButtonText>Buscar pelo código</ScanButtonText></ScanButton></>}</Bar>{message ? <Detail style={{ marginHorizontal: 18 }}>{message}</Detail> : null}
    {section === 'resumo' && <ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 40 }}><DashboardGrid><MetricCard><MaterialCommunityIcons name="archive-outline" size={22} color="#7c3aed" /><MetricLabel>Bens cadastrados</MetricLabel><MetricValue>{assets.length}</MetricValue></MetricCard><MetricCard><MaterialCommunityIcons name="wrench-outline" size={22} color="#d97706" /><MetricLabel>Em manutenção</MetricLabel><MetricValue>{assets.filter(item => item.status === 'maintenance').length}</MetricValue></MetricCard><MetricCard><MaterialCommunityIcons name="clipboard-check-outline" size={22} color="#0f766e" /><MetricLabel>Inventários abertos</MetricLabel><MetricValue>{inventories.filter(item => item.status === 'open').length}</MetricValue></MetricCard><MetricCard><MaterialCommunityIcons name="swap-horizontal" size={22} color="#0284C7" /><MetricLabel>Movimentações</MetricLabel><MetricValue>{movements.length}</MetricValue></MetricCard></DashboardGrid><DashboardCard><SectionTitle>Bens por situação</SectionTitle>{statusSummary.map(item => <ChartRow key={item.label}><ChartLabel>{item.label}</ChartLabel><ChartTrack><ChartBar width={(item.count / maxStatus) * 100} /></ChartTrack><ChartCount>{item.count}</ChartCount></ChartRow>)}</DashboardCard><DashboardCard><SectionTitle>Principais categorias</SectionTitle>{categorySummary.length ? categorySummary.map(([category, count]) => <ChartRow key={category}><ChartLabel>{category}</ChartLabel><ChartTrack><ChartBar width={(count / Math.max(1, categorySummary[0][1])) * 100} /></ChartTrack><ChartCount>{count}</ChartCount></ChartRow>) : <Detail>Nenhum bem cadastrado.</Detail>}</DashboardCard><DashboardCard><SectionTitle>Últimas movimentações</SectionTitle>{movements.slice(0, 5).map(item => <Row key={item.id} style={{ marginBottom: 11 }}><MaterialCommunityIcons name="swap-horizontal-circle-outline" size={22} color="#0284C7" /><Info><Title>{item.assetIdentifier || item.assetId || 'Bem não informado'}</Title><Detail>{item.type || 'Movimentação'} · {item.toDepartmentName || item.departmentName || 'Destino não informado'}</Detail><Detail>{date(item.createdAt)} · {item.createdByName || 'Responsável não informado'}</Detail></Info></Row>)}{!movements.length && <Detail>Nenhuma movimentação registrada.</Detail>}</DashboardCard><DashboardCard><SectionTitle>Inventários recentes</SectionTitle>{inventories.slice(0, 4).map(item => <Row key={item.id} style={{ marginBottom: 10 }}><MaterialCommunityIcons name="clipboard-list-outline" size={22} color="#0f766e" /><Info><Title>{item.identifier || item.name || 'Inventário patrimonial'}</Title><Detail>{item.status === 'open' ? 'Aberto' : item.status || 'Concluído'} · iniciado em {date(item.startedAt || item.createdAt)}</Detail></Info></Row>)}{!inventories.length && <Detail>Nenhum inventário cadastrado.</Detail>}</DashboardCard></ScrollView>}
    {section === 'bens' && <><FlatList data={filtered} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 100 }} ListEmptyComponent={<Empty>Nenhum bem encontrado.</Empty>} renderItem={({ item }) => (<Card><Row><MaterialCommunityIcons name="archive-outline" size={29} color="#7c3aed" /><Info><Title>{item.tombNumber || 'Sem tombamento'} · {item.description}</Title><Detail>{item.category || 'Sem categoria'} · {item.departmentName || 'Setor não informado'}</Detail><Detail>{STATUS[item.status] || item.status || 'Não informado'} · Conservação: {CONSERVATION[item.conservationState] || 'Não informado'}</Detail><Detail>Responsável: {item.responsibleName || 'Não informado'}</Detail></Info></Row></Card>)} /><FloatingAction accessibilityLabel="Adicionar bem patrimonial" onPress={() => setSection('novo')}><MaterialCommunityIcons name="plus" size={30} color="#fff" /></FloatingAction></>}
    {section === 'novo' && <ScrollView contentContainerStyle={{ paddingBottom: 40 }}><FormCard><Title>Novo bem patrimonial</Title><ScanButton onPress={() => openScanner('form')}><MaterialCommunityIcons name="barcode-scan" size={20} color="#0284C7" /><ScanButtonText>Ler QR Code ou código de barras</ScanButtonText></ScanButton>{[['tombNumber', 'Número de tombamento'], ['description', 'Descrição *'], ['category', 'Categoria'], ['departmentName', 'Setor'], ['location', 'Localização'], ['responsibleName', 'Responsável'], ['acquisitionValue', 'Valor de aquisição']].map(([key, label]) => <Fragment key={key}><Label>{label}</Label><Input value={form[key]} onChangeText={value => setForm({ ...form, [key]: value })} placeholder={label} placeholderTextColor="#94a3b8" /></Fragment>)}<Label>Conservação</Label><Horizontal>{Object.entries(CONSERVATION).map(([key, label]) => <Chip key={key} active={form.conservationState === key} onPress={() => setForm({ ...form, conservationState: key })}><ChipText active={form.conservationState === key}>{label}</ChipText></Chip>)}</Horizontal><Action disabled={busy} onPress={createAsset}><ActionText>Cadastrar bem</ActionText></Action></FormCard></ScrollView>}
    {section === 'detalhe' && selectedAsset && <ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 40 }}><FormCard><Title>{selectedAsset.tombNumber || 'Bem patrimonial'}</Title><Detail>{selectedAsset.description}</Detail><Detail>Categoria: {selectedAsset.category || 'Não informada'}</Detail><Detail>Setor: {selectedAsset.departmentName || 'Não informado'}</Detail><Detail>Localização: {selectedAsset.location || 'Não informada'}</Detail><Detail>Responsável: {selectedAsset.responsibleName || 'Não informado'}</Detail><Detail>Status: {STATUS[selectedAsset.status] || selectedAsset.status || 'Não informado'}</Detail>{selectedAsset.qrCodeUrl ? <Detail>QR Code salvo para impressão no portal.</Detail> : null}</FormCard></ScrollView>}
    <Modal visible={scannerVisible} animationType="slide" onRequestClose={() => setScannerVisible(false)}><CameraView style={{ flex: 1 }} facing="back" onBarcodeScanned={handleScan} barcodeScannerSettings={{ barcodeTypes: ['qr', 'ean13', 'ean8', 'code128', 'code39', 'upc_a', 'upc_e'] }} /><ScannerOverlay><ScannerSheet><Title>Leia o código do bem</Title><Detail>Aponte a câmera para o QR Code ou código de barras.</Detail><TouchableOpacity onPress={() => setScannerVisible(false)}><ActionText style={{ color: '#0284C7', marginTop: 14, textAlign: 'center' }}>Cancelar</ActionText></TouchableOpacity></ScannerSheet></ScannerOverlay></Modal>
    {section === 'movimentos' && <><FlatList data={movements} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 100 }} ListEmptyComponent={<Empty>Nenhuma movimentação registrada.</Empty>} renderItem={({ item }) => (<Card><Title>{item.assetIdentifier || item.assetId || 'Bem não informado'}</Title><Detail>{item.type || 'Movimentação'} · {item.toDepartmentName || item.departmentName || 'Destino não informado'}</Detail><Detail>{date(item.createdAt)} · {item.createdByName || 'Responsável não informado'}</Detail></Card>)} /><FloatingAction accessibilityLabel="Adicionar movimentação" onPress={() => setSection('novo-movimento')}><MaterialCommunityIcons name="plus" size={30} color="#fff" /></FloatingAction></>}
    {section === 'novo-movimento' && <ScanButton onPress={() => openScanner('movement')}><MaterialCommunityIcons name="barcode-scan" size={20} color="#0284C7" /><ScanButtonText>Identificar bem pelo código</ScanButtonText></ScanButton>}
    {section === 'novo-movimento' && <ScrollView contentContainerStyle={{ paddingBottom: 40 }}><FormCard><Title>Nova movimentação</Title><Label>ID do bem</Label><Input value={move.assetId} onChangeText={assetId => setMove({ ...move, assetId })} placeholder="Cole o ID do bem" placeholderTextColor="#94a3b8" /><Label>Tipo</Label><Horizontal>{[['transfer', 'Transferência'], ['loan', 'Empréstimo'], ['maintenance', 'Manutenção'], ['return', 'Retorno'], ['writeoff', 'Baixa']].map(([key, label]) => <Chip key={key} active={move.type === key} onPress={() => setMove({ ...move, type: key })}><ChipText active={move.type === key}>{label}</ChipText></Chip>)}</Horizontal><Label>Setor/localização de destino</Label><Input value={move.departmentName} onChangeText={departmentName => setMove({ ...move, departmentName })} placeholder="Destino" placeholderTextColor="#94a3b8" /><Label>Responsável</Label><Input value={move.responsibleName} onChangeText={responsibleName => setMove({ ...move, responsibleName })} placeholder="Responsável" placeholderTextColor="#94a3b8" /><Label>Motivo *</Label><Input value={move.reason} onChangeText={reason => setMove({ ...move, reason })} placeholder="Motivo da movimentação" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={moveAsset}><ActionText>Registrar movimentação</ActionText></Action></FormCard></ScrollView>}
    {section === 'inventarios' && <><FormCard><Title>Abrir inventário</Title><Input value={inventoryName} onChangeText={setInventoryName} placeholder="Ex.: Inventário anual 2026" placeholderTextColor="#94a3b8" /><Action disabled={busy || !inventoryName.trim()} onPress={() => { run('createInventory', { name: inventoryName.trim() }, 'Inventário aberto.'); setInventoryName(''); }}><ActionText>Abrir inventário</ActionText></Action></FormCard><FlatList data={inventories} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhum inventário cadastrado.</Empty>} renderItem={({ item }) => <Card><Title>{item.identifier || item.name}</Title><Detail>{item.name || 'Inventário patrimonial'} · {item.status === 'open' ? 'Aberto' : item.status || 'Concluído'}</Detail><Detail>Início: {date(item.startedAt || item.createdAt)}</Detail></Card>} /></>}
    {section === 'novo' && <ScanButton onPress={chooseAssetImage}><MaterialCommunityIcons name="image-plus" size={20} color="#0284C7" /><ScanButtonText>Anexar imagem do bem</ScanButtonText></ScanButton>}
    {section === 'novo' && form.imageUri ? <ImagePreview source={{ uri: form.imageUri }} /> : null}
  </PortalBackground>;
}
