import { MaterialCommunityIcons } from '@expo/vector-icons';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, ScrollView, TextInput } from 'react-native';
import styled from 'styled-components/native';

import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';
import { runAdministrativeCommand } from '../../services/AdministrativeCommand';
import { firestore } from '../../services/firebaseConfig';

const Bar = styled.View`padding: 14px 18px 6px;`;
const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`;
const ChipText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.card};`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`;
const Row = styled.View`flex-direction: row; align-items: center;`;
const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`;
const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`;
const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px;`;
const DetailCard = styled(PortalCard)`margin: 18px;`;
const Label = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; font-weight: 800; margin-top: 14px;`;
const Value = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; line-height: 22px; margin-top: 4px;`;
const Tabs = styled.View`flex-direction: row; flex-wrap: wrap; padding: 14px 18px 0;`;
const Tab = styled.TouchableOpacity`padding: 10px 12px; margin: 0 7px 8px 0; border-radius: 10px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card};`;
const TabText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 900;`;
const Input = styled(TextInput)`min-height: 96px; margin-top: 10px; padding: 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt}; text-align-vertical: top;`;
const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary};`;
const ActionText = styled.Text`color: #fff; font-weight: 900;`;
const STATUS = { active: 'Ativo', suspended: 'Suspenso', closed: 'Encerrado' };
const date = value => value?.toDate ? value.toDate().toLocaleDateString('pt-BR') : value ? new Date(value).toLocaleDateString('pt-BR') : 'Não informado';
const money = value => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });

export default function AdminContratosScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules();
  const [items, setItems] = useState([]); const [status, setStatus] = useState('Todas'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState(null); const [tab, setTab] = useState('dados'); const [activity, setActivity] = useState({ type: 'inspection', description: '', measuredValue: '' }); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!canUseAdminApp('contratos')) return undefined; return onSnapshot(query(collection(firestore, 'contracts'), orderBy('createdAt', 'desc')), snapshot => setItems(snapshot.docs.map(row => ({ id: row.id, ...row.data() }))), () => setItems([])); }, [canUseAdminApp]);
  const visible = useMemo(() => items.filter(item => { const text = `${item.identifier || ''} ${item.contractNumber || ''} ${item.supplierName || ''} ${item.object || ''}`.toLowerCase(); return (status === 'Todas' || item.status === status) && (!search.trim() || text.includes(search.toLowerCase().trim())); }), [items, search, status]);
  if (!canUseAdminApp('contratos')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  const saveActivity = async () => { if (!activity.description.trim()) return Alert.alert('Atenção', 'Descreva a atividade registrada.'); setBusy(true); try { const action = { inspection: 'addInspection', occurrence: 'addOccurrence', measurement: 'addMeasurement', obligation: 'addObligation' }[activity.type]; await runAdministrativeCommand('contratos', action, { contractId: selected.id, description: activity.description.trim(), measuredValue: activity.measuredValue }); setActivity({ type: 'inspection', description: '', measuredValue: '' }); Alert.alert('Sucesso', 'Atividade registrada.'); } catch (error) { Alert.alert('Erro', error.message || 'Não foi possível registrar a atividade.'); } finally { setBusy(false); } };
  if (selected) return <PortalBackground><PortalScreenHeader navigation={{ goBack: () => setSelected(null) }} eyebrow="Área administrativa" title="Central do contrato" subtitle={selected.identifier || selected.contractNumber || selected.id} /><Tabs>{[['dados', 'Dados'], ['execucao', 'Execução'], ['atividade', 'Registrar atividade']].map(([id, label]) => <Tab key={id} active={tab === id} onPress={() => setTab(id)}><TabText active={tab === id}>{label}</TabText></Tab>)}</Tabs><DetailCard>
    {tab === 'dados' && <><Label>Contrato</Label><Value>{selected.contractNumber || selected.identifier || 'Não informado'}</Value><Label>Fornecedor</Label><Value>{selected.supplierName || 'Não informado'}</Value><Label>Objeto</Label><Value>{selected.object || 'Não informado'}</Value><Label>Vigência</Label><Value>{date(selected.startsAt)} a {date(selected.endsAt)}</Value><Label>Valor atualizado</Label><Value>{money(selected.currentValue)}</Value><Label>Situação</Label><Value>{STATUS[selected.status] || selected.status || 'Não informado'}</Value></>}
    {tab === 'execucao' && <><Label>Valor contratado</Label><Value>{money(selected.currentValue || selected.initialValue)}</Value><Label>Valor executado</Label><Value>{money(selected.executedValue)}</Value><Label>Saldo contratual</Label><Value>{money(Number(selected.currentValue || selected.initialValue || 0) - Number(selected.executedValue || 0))}</Value><Label>Gestor</Label><Value>{selected.managerName || 'Não definido'}</Value><Label>Fiscal titular</Label><Value>{selected.inspectorName || 'Não definido'}</Value></>}
    {tab === 'atividade' && <><Label>Tipo de registro</Label><Horizontal><Chip active={activity.type === 'inspection'} onPress={() => setActivity({ ...activity, type: 'inspection' })}><ChipText active={activity.type === 'inspection'}>Fiscalização</ChipText></Chip><Chip active={activity.type === 'occurrence'} onPress={() => setActivity({ ...activity, type: 'occurrence' })}><ChipText active={activity.type === 'occurrence'}>Ocorrência</ChipText></Chip><Chip active={activity.type === 'measurement'} onPress={() => setActivity({ ...activity, type: 'measurement' })}><ChipText active={activity.type === 'measurement'}>Medição</ChipText></Chip><Chip active={activity.type === 'obligation'} onPress={() => setActivity({ ...activity, type: 'obligation' })}><ChipText active={activity.type === 'obligation'}>Obrigação</ChipText></Chip></Horizontal>{activity.type === 'measurement' && <><Label>Valor medido</Label><Search value={activity.measuredValue} onChangeText={measuredValue => setActivity({ ...activity, measuredValue })} keyboardType="decimal-pad" placeholder="0,00" placeholderTextColor="#94a3b8" /></>}<Label>Descrição</Label><Input multiline value={activity.description} onChangeText={description => setActivity({ ...activity, description })} placeholder="Descreva a verificação, evidência ou ocorrência." placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={saveActivity}><ActionText>{busy ? 'Registrando...' : 'Registrar atividade'}</ActionText></Action></>}
  </DetailCard></PortalBackground>;
  return <PortalBackground><PortalScreenHeader navigation={navigation} eyebrow="Área administrativa" title="Fiscalização de Contratos" subtitle="Acompanhe vigência, execução, ocorrências e obrigações." /><Bar><Horizontal>{['Todas', 'active', 'suspended', 'closed'].map(item => <Chip key={item} active={status === item} onPress={() => setStatus(item)}><ChipText active={status === item}>{STATUS[item] || item}</ChipText></Chip>)}</Horizontal><Search value={search} onChangeText={setSearch} placeholder="Buscar contrato, fornecedor ou objeto" placeholderTextColor="#94a3b8" /></Bar><FlatList data={visible} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 36 }} ListEmptyComponent={<Empty>Nenhum contrato encontrado.</Empty>} renderItem={({ item }) => <Card onPress={() => { setSelected(item); setTab('dados'); }}><Row><MaterialCommunityIcons name="file-sign" size={29} color="#0f766e" /><Info><Title>{item.identifier || item.contractNumber || 'Contrato sem identificação'}</Title><Detail>{item.supplierName || 'Fornecedor não informado'}</Detail><Detail numberOfLines={2}>{item.object || 'Objeto não informado'}</Detail><Detail>{STATUS[item.status] || item.status || 'Não informado'} · Vigência até {date(item.endsAt)}</Detail></Info><MaterialCommunityIcons name="chevron-right" size={22} color="#94a3b8" /></Row></Card>} /></PortalBackground>;
}
