import { MaterialCommunityIcons } from '@expo/vector-icons';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as ImagePicker from 'expo-image-picker';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Alert, FlatList, Modal, ScrollView, TextInput, TouchableOpacity } from 'react-native';
import styled from 'styled-components/native';

import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';
import { runAdministrativeCommand } from '../../services/AdministrativeCommand';
import { firestore } from '../../services/firebaseConfig';
import { uploadFileToStorage } from '../../services/storageService';

const Bar = styled.View`padding: 14px 18px 6px;`;
const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`;
const ChipText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.card};`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`;
const Row = styled.View`flex-direction: row; align-items: center;`;
const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`;
const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`;
const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px;`;
const FormCard = styled(PortalCard)`margin: 18px;`;
const Label = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 13px; font-weight: 800; margin-top: 12px;`;
const Input = styled(TextInput)`height: 44px; margin-top: 7px; padding: 0 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt};`;
const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary};`;
const ActionText = styled.Text`color: #fff; font-weight: 900;`;
const FullWidthAction = styled(Action)`margin-left: 0; margin-right: 0;`;
const FloatingAction = styled.TouchableOpacity`position: absolute; right: 22px; bottom: 26px; width: 56px; height: 56px; border-radius: 28px; align-items: center; justify-content: center; background-color: ${({ theme }) => theme.portal.primary}; elevation: 6; shadow-color: #000; shadow-opacity: .22; shadow-radius: 7px; shadow-offset: 0px 4px;`;
const ScanButton = styled.TouchableOpacity`flex-direction: row; align-items: center; justify-content: center; margin-top: 12px; padding: 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.primary}; background-color: ${({ theme }) => `${theme.portal.primary}16`};`;
const ScanButtonText = styled.Text`margin-left: 8px; color: ${({ theme }) => theme.portal.primary}; font-weight: 900;`;
const ImagePreview = styled.Image`width: 100%; height: 150px; margin-top: 12px; border-radius: 10px;`;
const ScannerContainer = styled.View`flex: 1;`;
const ScannerOverlay = styled.View`position: absolute; top: 0; right: 0; bottom: 0; left: 0; justify-content: flex-end; background-color: rgba(0,0,0,.25);`;
const ScannerSheet = styled.View`padding: 20px; background-color: ${({ theme }) => theme.portal.card}; border-top-left-radius: 22px; border-top-right-radius: 22px;`;
const DashboardGrid = styled.View`flex-direction: row; flex-wrap: wrap; justify-content: space-between;`;
const MetricCard = styled(PortalCard)`width: 48%; margin: 0 0 10px; padding: 14px;`;
const MetricLabel = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 11px; font-weight: 700; margin-top: 8px;`;
const MetricValue = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 23px; font-weight: 900; margin-top: 3px;`;
const SectionTitle = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 16px; font-weight: 900; margin-bottom: 12px;`;
const ChartRow = styled.View`flex-direction: row; align-items: center; margin-top: 9px;`;
const ChartLabel = styled.Text`width: 92px; color: ${({ theme }) => theme.portal.muted}; font-size: 11px;`;
const ChartTrack = styled.View`flex: 1; height: 9px; border-radius: 5px; background-color: ${({ theme }) => theme.portal.pageAlt}; overflow: hidden;`;
const ChartBar = styled.View`height: 100%; border-radius: 5px; background-color: ${({ theme }) => theme.portal.primary}; width: ${({ width }) => `${width}%`};`;
const ChartCount = styled.Text`width: 28px; margin-left: 7px; color: ${({ theme }) => theme.portal.text}; font-size: 11px; font-weight: 800; text-align: right;`;
const DashboardCard = styled(PortalCard)`margin: 0 0 12px; padding: 16px;`;
const STATUS = { requested: 'Solicitado', awaiting_authorization: 'Aguardando autorização', authorized: 'Autorizado', separating: 'Em separação', delivered: 'Entregue', received: 'Recebido', cancelled: 'Cancelado' };
const MOVEMENTS = { entry: 'Entrada', exit: 'Saída', transfer: 'Transferência', return: 'Devolução', adjustment: 'Ajuste', loss: 'Perda' };
const date = value => value?.toDate ? value.toDate().toLocaleDateString('pt-BR') : value ? new Date(value).toLocaleDateString('pt-BR') : 'Não informado';
const useRows = name => { const [rows, setRows] = useState([]); useEffect(() => onSnapshot(query(collection(firestore, name), orderBy('createdAt', 'desc')), snap => setRows(snap.docs.map(row => ({ id: row.id, ...row.data() }))), () => setRows([])), [name]); return rows; };

export default function AdminAlmoxarifadoScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules(); const products = useRows('inventoryProducts'); const warehouses = useRows('inventoryWarehouses'); const movements = useRows('inventoryMovements'); const requests = useRows('materialRequests');
  const [section, setSection] = useState('resumo'); const [search, setSearch] = useState(''); const [form, setForm] = useState({ code: '', description: '', category: '', unit: 'UN', minimumStock: '0', maximumStock: '0', imageUri: '' }); const [request, setRequest] = useState({ productId: '', warehouseId: '', quantity: '1', justification: '', departmentName: '' }); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [scannerVisible, setScannerVisible] = useState(false); const [permission, requestPermission] = useCameraPermissions(); const descriptionRef = useRef(null);
  const run = async (action, payload, success) => { setBusy(true); setMessage(''); try { await runAdministrativeCommand('almoxarifado', action, payload); setMessage(success); } catch (error) { setMessage(error.message || 'Não foi possível concluir a operação.'); } finally { setBusy(false); } };
  const filteredProducts = useMemo(() => products.filter(item => `${item.code} ${item.description} ${item.category}`.toLowerCase().includes(search.toLowerCase())), [products, search]);
  const lowStock = useMemo(() => products.filter(item => Number(item.currentStock || 0) <= Number(item.minimumStock || 0)), [products]);
  const movementSummary = useMemo(() => Object.entries(MOVEMENTS).map(([type, label]) => ({ label, count: movements.filter(item => item.type === type).length })).filter(item => item.count > 0), [movements]);
  const maxMovement = Math.max(1, ...movementSummary.map(item => item.count));
  const headerNavigation = { ...navigation, goBack: () => section === 'novo-produto' ? setSection('produtos') : section === 'nova-requisicao' ? setSection('requisicoes') : navigation.goBack() };
  if (!canUseAdminApp('almoxarifado')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  const chooseProductImage = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.85 }); if (!result.canceled) setForm(current => ({ ...current, imageUri: result.assets[0].uri })); };
  const submitProduct = async () => { if (!form.description.trim()) return Alert.alert('Atenção', 'Informe a descrição do produto.'); setBusy(true); try { const imageUrl = form.imageUri ? await uploadFileToStorage(form.imageUri, `almoxarifado/produtos/${form.code || Date.now()}`) : ''; await runAdministrativeCommand('almoxarifado', 'createProduct', { ...form, imageUri: undefined, imageUrl }); setMessage('Produto cadastrado com sucesso.'); setForm({ code: '', description: '', category: '', unit: 'UN', minimumStock: '0', maximumStock: '0', imageUri: '' }); setSection('produtos'); } catch (error) { setMessage(error.message || 'Não foi possível cadastrar o produto.'); } finally { setBusy(false); } };
  const openScanner = async () => { if (!permission?.granted) { const result = await requestPermission(); if (!result.granted) return Alert.alert('Permissão necessária', 'Permita o acesso à câmera para ler o código do produto.'); } setScannerVisible(true); };
  const handleScan = ({ data }) => { if (!data) return; setScannerVisible(false); const code = String(data).trim(); const existing = products.find(item => String(item.code || item.barcode || item.codigo || '').trim() === code); if (existing) { setForm(current => ({ ...current, ...existing, code })); setMessage('Produto encontrado. Confira os dados antes de salvar.'); } else { setForm(current => ({ ...current, code })); setMessage('Código novo. Informe a descrição do produto.'); setTimeout(() => descriptionRef.current?.focus(), 250); } };
  const submitRequest = () => { const product = products.find(item => item.id === request.productId); if (!product || !request.warehouseId || !request.justification.trim()) return Alert.alert('Atenção', 'Informe produto, depósito e justificativa.'); run('createRequest', { warehouseId: request.warehouseId, departmentName: request.departmentName, justification: request.justification, items: [{ productId: product.id, productDescription: product.description, quantity: request.quantity }] }, 'Requisição criada com sucesso.'); setRequest({ productId: '', warehouseId: '', quantity: '1', justification: '', departmentName: '' }); };
  const advance = item => { const next = { requested: 'awaiting_authorization', awaiting_authorization: 'authorized', authorized: 'separating', separating: 'delivered', delivered: 'received' }[item.status]; if (next) run('transitionRequest', { id: item.id, status: next }, 'Requisição atualizada.'); };
  return <PortalBackground><PortalScreenHeader navigation={headerNavigation} eyebrow="Área administrativa" title="Almoxarifado" subtitle="Controle materiais, depósitos, requisições e movimentações." /><Bar><Horizontal>{[['resumo', 'Visão geral'], ['produtos', 'Produtos'], ['depositos', 'Depósitos'], ['requisicoes', 'Requisições'], ['movimentacoes', 'Movimentações']].map(([id, label]) => <Chip key={id} active={section === id} onPress={() => setSection(id)}><ChipText active={section === id}>{label}</ChipText></Chip>)}</Horizontal>{(section === 'produtos' || section === 'movimentacoes') && <Search value={search} onChangeText={setSearch} placeholder="Buscar item" placeholderTextColor="#94a3b8" />}</Bar>
    {message ? <Detail style={{ marginHorizontal: 18 }}>{message}</Detail> : null}
    {section === 'resumo' && <ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 40 }}><DashboardGrid><MetricCard><MaterialCommunityIcons name="package-variant-closed" size={22} color="#0284C7" /><MetricLabel>Produtos cadastrados</MetricLabel><MetricValue>{products.length}</MetricValue></MetricCard><MetricCard><MaterialCommunityIcons name="warehouse" size={22} color="#0f766e" /><MetricLabel>Depósitos</MetricLabel><MetricValue>{warehouses.length}</MetricValue></MetricCard><MetricCard><MaterialCommunityIcons name="swap-horizontal" size={22} color="#d97706" /><MetricLabel>Movimentações</MetricLabel><MetricValue>{movements.length}</MetricValue></MetricCard><MetricCard><MaterialCommunityIcons name="clipboard-alert-outline" size={22} color="#dc2626" /><MetricLabel>Requisições pendentes</MetricLabel><MetricValue>{requests.filter(item => !['received', 'cancelled'].includes(item.status)).length}</MetricValue></MetricCard></DashboardGrid><DashboardCard><SectionTitle>Movimentações por tipo</SectionTitle>{movementSummary.length ? movementSummary.map(item => <ChartRow key={item.label}><ChartLabel>{item.label}</ChartLabel><ChartTrack><ChartBar width={(item.count / maxMovement) * 100} /></ChartTrack><ChartCount>{item.count}</ChartCount></ChartRow>) : <Detail>Nenhuma movimentação registrada.</Detail>}</DashboardCard><DashboardCard><SectionTitle>Estoque baixo</SectionTitle>{lowStock.slice(0, 5).map(item => <Row key={item.id} style={{ marginBottom: 10 }}><MaterialCommunityIcons name="alert-circle-outline" size={21} color="#dc2626" /><Info><Title>{item.description || 'Produto sem descrição'}</Title><Detail>{item.currentStock || 0} {item.unit || ''} disponíveis · mínimo {item.minimumStock || 0}</Detail></Info></Row>)}{!lowStock.length && <Detail>Nenhum produto abaixo do mínimo.</Detail>}</DashboardCard><DashboardCard><SectionTitle>Últimas movimentações</SectionTitle>{movements.slice(0, 5).map(item => <Row key={item.id} style={{ marginBottom: 11 }}><MaterialCommunityIcons name={item.type === 'exit' ? 'arrow-up-circle-outline' : 'arrow-down-circle-outline'} size={22} color={item.type === 'exit' ? '#dc2626' : '#0f766e'} /><Info><Title>{item.productDescription || 'Produto não informado'}</Title><Detail>{MOVEMENTS[item.type] || item.type || 'Movimentação'} · {item.quantity || 0} · {date(item.createdAt)}</Detail></Info></Row>)}{!movements.length && <Detail>Nenhuma movimentação registrada.</Detail>}</DashboardCard></ScrollView>}
    {section === 'produtos' && <><FlatList data={filteredProducts} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 100 }} ListEmptyComponent={<Empty>Nenhum produto encontrado.</Empty>} renderItem={({ item }) => (<Card><Row><MaterialCommunityIcons name="package-variant-closed" size={28} color="#0f766e" /><Info><Title>{item.code || 'Sem código'} · {item.description}</Title><Detail>{item.category || 'Sem categoria'} · Estoque: {item.currentStock || 0} {item.unit || ''}</Detail><Detail>Mínimo: {item.minimumStock || 0} · Máximo: {item.maximumStock || 0}</Detail></Info></Row></Card>)} /><FloatingAction accessibilityLabel="Adicionar produto" onPress={() => setSection('novo-produto')}><MaterialCommunityIcons name="plus" size={30} color="#fff" /></FloatingAction></>}
    {section === 'novo-produto' && <ScrollView contentContainerStyle={{ paddingBottom: 40 }}><FormCard><Title>Novo produto</Title><ScanButton onPress={openScanner}><MaterialCommunityIcons name="barcode-scan" size={21} color="#0284C7" /><ScanButtonText>Ler código de barras ou QR Code</ScanButtonText></ScanButton><Label>Código</Label><Input value={form.code} onChangeText={code => setForm({ ...form, code })} placeholder="Código" placeholderTextColor="#94a3b8" /><Label>Descrição *</Label><Input ref={descriptionRef} value={form.description} onChangeText={description => setForm({ ...form, description })} placeholder="Descrição" placeholderTextColor="#94a3b8" /><Label>Categoria</Label><Input value={form.category} onChangeText={category => setForm({ ...form, category })} placeholder="Categoria" placeholderTextColor="#94a3b8" /><Label>Unidade</Label><Input value={form.unit} onChangeText={unit => setForm({ ...form, unit })} placeholder="UN" placeholderTextColor="#94a3b8" /><FullWidthAction disabled={busy} onPress={submitProduct}><ActionText>Salvar produto</ActionText></FullWidthAction></FormCard></ScrollView>}
    <Modal visible={scannerVisible} animationType="slide" onRequestClose={() => setScannerVisible(false)}><ScannerContainer><CameraView style={{ flex: 1 }} facing="back" onBarcodeScanned={handleScan} barcodeScannerSettings={{ barcodeTypes: ['qr', 'ean13', 'ean8', 'code128', 'code39', 'upc_a', 'upc_e'] }} /><ScannerOverlay><ScannerSheet><Title>Leia o código do produto</Title><Detail>Aponte a câmera para o QR Code ou código de barras.</Detail><TouchableOpacity onPress={() => setScannerVisible(false)}><ActionText style={{ color: '#0284C7', marginTop: 14, textAlign: 'center' }}>Cancelar</ActionText></TouchableOpacity></ScannerSheet></ScannerOverlay></ScannerContainer></Modal>
    {section === 'depositos' && <FlatList data={warehouses} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhum depósito cadastrado.</Empty>} renderItem={({ item }) => <Card><Title>{item.code || 'Sem código'} · {item.name}</Title><Detail>{item.location || 'Localização não informada'}</Detail><Detail>Responsável: {item.responsibleName || 'Não informado'}</Detail></Card>} />}
    {section === 'requisicoes' && <><FlatList data={requests} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 100 }} ListEmptyComponent={<Empty>Nenhuma requisição encontrada.</Empty>} renderItem={({ item }) => (<Card><Row><MaterialCommunityIcons name="clipboard-list-outline" size={28} color="#0284C7" /><Info><Title>{item.identifier || item.id}</Title><Detail>{item.requesterName || 'Solicitante não informado'} · {item.departmentName || 'Setor não informado'}</Detail><Detail>{STATUS[item.status] || item.status || 'Não informado'} · {date(item.createdAt)}</Detail></Info><Chip active={false} onPress={() => advance(item)}><ChipText active={false}>Avançar</ChipText></Chip></Row></Card>)} /><FloatingAction accessibilityLabel="Adicionar requisição" onPress={() => setSection('nova-requisicao')}><MaterialCommunityIcons name="plus" size={30} color="#fff" /></FloatingAction></>}
    {section === 'nova-requisicao' && <FormCard><Title>Solicitar material</Title><Label>Produto (ID)</Label><Input value={request.productId} onChangeText={productId => setRequest({ ...request, productId })} placeholder="Cole o ID do produto" placeholderTextColor="#94a3b8" /><Label>Depósito (ID)</Label><Input value={request.warehouseId} onChangeText={warehouseId => setRequest({ ...request, warehouseId })} placeholder="Cole o ID do depósito" placeholderTextColor="#94a3b8" /><Label>Quantidade</Label><Input value={request.quantity} onChangeText={quantity => setRequest({ ...request, quantity })} keyboardType="numeric" placeholder="1" placeholderTextColor="#94a3b8" /><Label>Setor</Label><Input value={request.departmentName} onChangeText={departmentName => setRequest({ ...request, departmentName })} placeholder="Setor solicitante" placeholderTextColor="#94a3b8" /><Label>Justificativa *</Label><Input value={request.justification} onChangeText={justification => setRequest({ ...request, justification })} placeholder="Motivo da solicitação" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={submitRequest}><ActionText>Enviar requisição</ActionText></Action></FormCard>}
    {section === 'movimentacoes' && <FlatList data={movements.filter(item => `${item.productDescription} ${item.createdByName}`.toLowerCase().includes(search.toLowerCase()))} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhuma movimentação encontrada.</Empty>} renderItem={({ item }) => <Card><Title>{MOVEMENTS[item.type] || item.type || 'Movimentação'}</Title><Detail>{item.productDescription || 'Produto não informado'} · Quantidade: {item.quantity || 0}</Detail><Detail>{date(item.createdAt)} · {item.createdByName || 'Responsável não informado'}</Detail></Card>} />}
    {section === 'novo-produto' && <ScanButton onPress={chooseProductImage}><MaterialCommunityIcons name="image-plus" size={21} color="#0284C7" /><ScanButtonText>Anexar imagem do produto</ScanButtonText></ScanButton>}
    {section === 'novo-produto' && form.imageUri ? <ImagePreview source={{ uri: form.imageUri }} /> : null}
  </PortalBackground>;
}
