import { MaterialCommunityIcons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, ScrollView, TextInput } from 'react-native';
import styled from 'styled-components/native';

import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';
import { runAdministrativeCommand } from '../../services/AdministrativeCommand';
import { firestore } from '../../services/firebaseConfig';
import { uploadFileToStorage } from '../../services/storageService';

const Bar = styled.View`padding: 14px 18px 6px;`;
const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`;
const ChipText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.card};`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`;
const Row = styled.View`flex-direction: row; align-items: center;`;
const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`;
const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`;
const Value = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; line-height: 22px; margin-top: 4px;`;
const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px;`;
const FormCard = styled(PortalCard)`margin: 18px;`;
const Label = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 13px; font-weight: 800; margin-top: 12px;`;
const Input = styled(TextInput)`min-height: 44px; margin-top: 7px; padding: 0 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt};`;
const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary};`;
const ActionText = styled.Text`color: #fff; font-weight: 900;`;
const FloatingAction = styled.TouchableOpacity`position: absolute; right: 22px; bottom: 26px; z-index: 20; width: 56px; height: 56px; border-radius: 28px; align-items: center; justify-content: center; background-color: ${({ theme }) => theme.portal.primary}; elevation: 12; shadow-color: #000; shadow-opacity: .22; shadow-radius: 7px; shadow-offset: 0px 4px;`;
const Evidence = styled.Image`width: 100%; height: 170px; margin-top: 12px; border-radius: 12px;`;
const DashboardGrid = styled.View`flex-direction: row; flex-wrap: wrap; justify-content: space-between;`;
const MetricCard = styled(PortalCard)`width: 48%; margin: 0 0 10px; padding: 14px;`;
const MetricLabel = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 11px; font-weight: 700; margin-top: 8px;`;
const MetricValue = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 23px; font-weight: 900; margin-top: 3px;`;
const DashboardCard = styled(PortalCard)`margin: 0 0 12px; padding: 16px;`;
const SectionTitle = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 16px; font-weight: 900; margin-bottom: 12px;`;
const STATUS = { open: 'Aberto', triage: 'Em triagem', assigned: 'Atribuída', in_progress: 'Em execução', awaiting_material: 'Aguardando material', awaiting_supplier: 'Aguardando fornecedor', completed: 'Concluída', validated: 'Validada', closed: 'Encerrada' };
const useRows = name => { const [rows, setRows] = useState([]); useEffect(() => onSnapshot(query(collection(firestore, name), orderBy('createdAt', 'desc')), snap => setRows(snap.docs.map(row => ({ id: row.id, ...row.data() }))), () => setRows([])), [name]); return rows; };
const date = value => value?.toDate ? value.toDate().toLocaleDateString('pt-BR') : value ? new Date(value).toLocaleDateString('pt-BR') : 'Não informado';

export default function AdminManutencaoScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules(); const tickets = useRows('maintenanceTickets'); const orders = useRows('maintenanceWorkOrders'); const plans = useRows('maintenancePlans'); const assets = useRows('assets');
  const [section, setSection] = useState('resumo'); const [search, setSearch] = useState(''); const [form, setForm] = useState({ assetId: '', subject: '', description: '', priority: 'normal', departmentName: '' }); const [order, setOrder] = useState({ ticketId: '', technicianName: '', supplierName: '', contractId: '', diagnosis: '', estimatedCost: '' }); const [plan, setPlan] = useState({ assetId: '', title: '', description: '', frequencyDays: '30', nextAt: '', responsibleName: '', contractId: '' }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [selectedWork, setSelectedWork] = useState(null);
  const run = async (action, payload, success) => { setBusy(true); setMessage(''); try { await runAdministrativeCommand('manutencao', action, payload); setMessage(success); } catch (error) { setMessage(error.message || 'Não foi possível concluir a operação.'); } finally { setBusy(false); } };
  const filteredTickets = useMemo(() => tickets.filter(item => `${item.identifier} ${item.subject} ${item.assetDescription} ${item.requesterName}`.toLowerCase().includes(search.toLowerCase())), [tickets, search]);
  const createTicket = () => { if (!form.subject.trim() || !form.description.trim()) return Alert.alert('Atenção', 'Informe o problema e a descrição.'); const asset = assets.find(item => item.id === form.assetId); run('createTicket', { ...form, assetIdentifier: asset?.tombNumber || asset?.identifier || '', assetDescription: asset?.description || '' }, 'Chamado aberto com sucesso.'); setForm({ assetId: '', subject: '', description: '', priority: 'normal', departmentName: '' }); };
  const createOrder = () => { if (!order.ticketId) return Alert.alert('Atenção', 'Selecione um chamado.'); run('createWorkOrder', order, 'Ordem de serviço criada.'); setOrder({ ticketId: '', technicianName: '', supplierName: '', contractId: '', diagnosis: '', estimatedCost: '' }); };
  const createPlan = () => { if (!plan.title.trim()) return Alert.alert('Atenção', 'Informe o título do plano.'); const asset = assets.find(item => item.id === plan.assetId); run('createPlan', { ...plan, assetIdentifier: asset?.tombNumber || asset?.identifier || '' }, 'Plano preventivo criado.'); setPlan({ assetId: '', title: '', description: '', frequencyDays: '30', nextAt: '', responsibleName: '', contractId: '' }); };
  const nextStatus = { open: 'triage', triage: 'assigned', assigned: 'in_progress', in_progress: 'completed', awaiting_material: 'in_progress', awaiting_supplier: 'in_progress', completed: 'validated', validated: 'closed' };
  const attachEvidence = async () => { if (!selectedWork) return; const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.8 }); if (result.canceled) return; setBusy(true); try { const imageUrl = await uploadFileToStorage(result.assets[0].uri, `manutencao/${selectedWork.kind}/${selectedWork.id}/evidencias`); await runAdministrativeCommand('manutencao', 'addEvidence', { collection: selectedWork.kind === 'ticket' ? 'maintenanceTickets' : 'maintenanceWorkOrders', id: selectedWork.id, imageUrl }); setMessage('Evidência fotográfica anexada.'); } catch (error) { setMessage(error.message || 'Não foi possível anexar a foto.'); } finally { setBusy(false); } };
  const advanceSelected = () => { if (!selectedWork) return; const next = nextStatus[selectedWork.status]; if (!next) return; run('transitionWorkOrder', { id: selectedWork.id, status: next }, 'Situação atualizada.'); setSelectedWork({ ...selectedWork, status: next }); };
  const activeTickets = tickets.filter(item => !['completed', 'validated', 'closed'].includes(item.status));
  const activeOrders = orders.filter(item => !['completed', 'validated', 'closed'].includes(item.status));
  const urgentTickets = tickets.filter(item => ['high', 'urgent', 'critical'].includes(item.priority));
  const headerNavigation = { ...navigation, goBack: () => section === 'novo' ? setSection('chamados') : section === 'ordens' ? setSection('ordens-list') : section === 'preventivas' ? setSection('preventivas-list') : navigation.goBack() };
  if (!canUseAdminApp('manutencao')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  if (selectedWork) return <PortalBackground><PortalScreenHeader navigation={{ goBack: () => setSelectedWork(null) }} eyebrow="Manutenção" title={selectedWork.kind === 'ticket' ? 'Detalhes do chamado' : 'Detalhes da ordem de serviço'} subtitle={selectedWork.identifier || selectedWork.id} /><ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 40 }}><FormCard><Title>{selectedWork.subject || selectedWork.description || 'Manutenção patrimonial'}</Title><Detail>Situação: {STATUS[selectedWork.status] || selectedWork.status || 'Aberta'}</Detail><Detail>Prioridade: {selectedWork.priority || 'Normal'}</Detail><Detail>Patrimônio: {selectedWork.assetIdentifier || selectedWork.assetDescription || 'Não informado'}</Detail><Detail>Responsável: {selectedWork.technicianName || selectedWork.requesterName || 'Não definido'}</Detail><Detail>Registrado em: {date(selectedWork.createdAt)}</Detail><Action disabled={busy || !nextStatus[selectedWork.status]} onPress={advanceSelected}><ActionText>Avançar situação</ActionText></Action><Action onPress={attachEvidence}><ActionText>Anexar foto/evidência</ActionText></Action>{selectedWork.description ? <><Label>Descrição</Label><Value>{selectedWork.description}</Value></> : null}{selectedWork.diagnosis ? <><Label>Diagnóstico e solução</Label><Value>{selectedWork.diagnosis}</Value></> : null}{selectedWork.evidenceUrl ? <Evidence source={{ uri: selectedWork.evidenceUrl }} /> : null}</FormCard></ScrollView></PortalBackground>;
  return <PortalBackground><PortalScreenHeader navigation={headerNavigation} eyebrow="Área administrativa" title="Manutenção Patrimonial" subtitle="Centralize chamados, ordens de serviço e planos preventivos." /><Bar><Horizontal>{[['resumo', 'Visão geral'], ['chamados', 'Chamados'], ['ordens-list', 'Ordens de serviço'], ['preventivas-list', 'Preventivas']].map(([id, label]) => <Chip key={id} active={section === id || (id === 'ordens-list' && section === 'ordens') || (id === 'preventivas-list' && section === 'preventivas')} onPress={() => setSection(id)}><ChipText active={section === id || (id === 'ordens-list' && section === 'ordens') || (id === 'preventivas-list' && section === 'preventivas')}>{label}</ChipText></Chip>)}</Horizontal>{section === 'chamados' && <Search value={search} onChangeText={setSearch} placeholder="Buscar chamado, patrimônio ou solicitante" placeholderTextColor="#94a3b8" />}</Bar>{message ? <Detail style={{ marginHorizontal: 18 }}>{message}</Detail> : null}
    {section === 'resumo' && <ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 40 }}><DashboardGrid><MetricCard><MaterialCommunityIcons name="tools" size={22} color="#d97706" /><MetricLabel>Chamados</MetricLabel><MetricValue>{tickets.length}</MetricValue></MetricCard><MetricCard><MaterialCommunityIcons name="clipboard-text-outline" size={22} color="#0284C7" /><MetricLabel>Ordens de serviço</MetricLabel><MetricValue>{orders.length}</MetricValue></MetricCard><MetricCard><MaterialCommunityIcons name="progress-wrench" size={22} color="#dc2626" /><MetricLabel>Em andamento</MetricLabel><MetricValue>{activeTickets.length + activeOrders.length}</MetricValue></MetricCard><MetricCard><MaterialCommunityIcons name="alert-outline" size={22} color="#b91c1c" /><MetricLabel>Prioridade alta</MetricLabel><MetricValue>{urgentTickets.length}</MetricValue></MetricCard></DashboardGrid><DashboardCard><SectionTitle>Chamados por situação</SectionTitle>{Object.entries(STATUS).filter(([key]) => tickets.some(item => item.status === key)).map(([key, label]) => <Detail key={key}>{label}: {tickets.filter(item => item.status === key).length}</Detail>)}</DashboardCard><DashboardCard><SectionTitle>Chamados recentes</SectionTitle>{tickets.slice(0, 6).map(item => <Row key={item.id} style={{ marginBottom: 11 }}><MaterialCommunityIcons name="tools" size={22} color={item.priority === 'high' || item.priority === 'urgent' ? '#dc2626' : '#d97706'} /><Info><Title>{item.identifier || item.subject || item.id}</Title><Detail>{item.subject || 'Problema não informado'} · {STATUS[item.status] || item.status || 'Aberto'}</Detail><Detail>{item.assetIdentifier || 'Sem patrimônio vinculado'} · {date(item.createdAt)}</Detail></Info></Row>)}{!tickets.length && <Detail>Nenhum chamado registrado.</Detail>}</DashboardCard><DashboardCard><SectionTitle>Ordens de serviço em aberto</SectionTitle>{activeOrders.slice(0, 5).map(item => <Row key={item.id} style={{ marginBottom: 10 }}><MaterialCommunityIcons name="clipboard-text-outline" size={22} color="#0284C7" /><Info><Title>{item.identifier || item.subject || item.id}</Title><Detail>{item.assetDescription || 'Patrimônio não informado'} · {STATUS[item.status] || item.status || 'Aberta'}</Detail><Detail>Técnico: {item.technicianName || 'Não definido'}</Detail></Info></Row>)}{!activeOrders.length && <Detail>Nenhuma ordem de serviço pendente.</Detail>}</DashboardCard><DashboardCard><SectionTitle>Planos preventivos</SectionTitle><Detail>{plans.length} plano(s) cadastrado(s)</Detail><Detail>{plans.filter(item => item.nextAt).length} com próxima execução definida</Detail></DashboardCard></ScrollView>}
    {section === 'chamados' && <><FlatList data={filteredTickets} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 100 }} ListEmptyComponent={<Empty>Nenhum chamado encontrado.</Empty>} renderItem={({ item }) => <Card onPress={() => setSelectedWork({ ...item, kind: 'ticket' })}><Row><MaterialCommunityIcons name="tools" size={29} color="#d97706" /><Info><Title>{item.identifier || item.subject || item.id}</Title><Detail>{item.subject || 'Problema não informado'} · {STATUS[item.status] || item.status || 'Aberto'}</Detail><Detail>{item.assetIdentifier || 'Sem patrimônio vinculado'} · {date(item.createdAt)}</Detail></Info><Chip active={false} onPress={() => nextStatus[item.status] && run('transitionWorkOrder', { id: item.id, status: nextStatus[item.status] }, 'Status atualizado.')}><ChipText active={false}>Avançar</ChipText></Chip></Row></Card>} /></>}
    {section === 'novo' && <FormCard><Title>Abrir chamado</Title><Label>Patrimônio</Label><Input value={form.assetId} onChangeText={assetId => setForm({ ...form, assetId })} placeholder="ID do bem (opcional)" placeholderTextColor="#94a3b8" /><Label>Problema *</Label><Input value={form.subject} onChangeText={subject => setForm({ ...form, subject })} placeholder="Descreva o problema" placeholderTextColor="#94a3b8" /><Label>Descrição *</Label><Input multiline value={form.description} onChangeText={description => setForm({ ...form, description })} placeholder="Detalhe a necessidade de manutenção" placeholderTextColor="#94a3b8" /><Label>Setor</Label><Input value={form.departmentName} onChangeText={departmentName => setForm({ ...form, departmentName })} placeholder="Setor" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={createTicket}><ActionText>Abrir chamado</ActionText></Action></FormCard>}
    {section === 'ordens' && <><FormCard><Title>Criar ordem de serviço</Title><Label>Chamado (ID) *</Label><Input value={order.ticketId} onChangeText={ticketId => setOrder({ ...order, ticketId })} placeholder="ID do chamado" placeholderTextColor="#94a3b8" /><Label>Técnico</Label><Input value={order.technicianName} onChangeText={technicianName => setOrder({ ...order, technicianName })} placeholder="Técnico responsável" placeholderTextColor="#94a3b8" /><Label>Fornecedor</Label><Input value={order.supplierName} onChangeText={supplierName => setOrder({ ...order, supplierName })} placeholder="Empresa/fornecedor" placeholderTextColor="#94a3b8" /><Label>Diagnóstico</Label><Input multiline value={order.diagnosis} onChangeText={diagnosis => setOrder({ ...order, diagnosis })} placeholder="Diagnóstico" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={createOrder}><ActionText>Criar ordem</ActionText></Action></FormCard><FlatList data={orders} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhuma ordem encontrada.</Empty>} renderItem={({ item }) => <Card onPress={() => setSelectedWork({ ...item, kind: 'order' })}><Title>{item.identifier || item.subject || item.id}</Title><Detail>{item.assetDescription || 'Patrimônio não informado'} · {STATUS[item.status] || item.status || 'Aberta'}</Detail><Detail>Técnico: {item.technicianName || 'Não definido'}</Detail></Card>} /></>}
    {section === 'preventivas' && <><FormCard><Title>Novo plano preventivo</Title><Label>Patrimônio</Label><Input value={plan.assetId} onChangeText={assetId => setPlan({ ...plan, assetId })} placeholder="ID do bem" placeholderTextColor="#94a3b8" /><Label>Título *</Label><Input value={plan.title} onChangeText={title => setPlan({ ...plan, title })} placeholder="Ex.: Revisão elétrica" placeholderTextColor="#94a3b8" /><Label>Periodicidade em dias</Label><Input value={plan.frequencyDays} onChangeText={frequencyDays => setPlan({ ...plan, frequencyDays })} keyboardType="numeric" placeholder="30" placeholderTextColor="#94a3b8" /><Label>Próxima execução</Label><Input value={plan.nextAt} onChangeText={nextAt => setPlan({ ...plan, nextAt })} placeholder="AAAA-MM-DD" placeholderTextColor="#94a3b8" /><Label>Descrição</Label><Input multiline value={plan.description} onChangeText={description => setPlan({ ...plan, description })} placeholder="Checklist e orientações" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={createPlan}><ActionText>Criar plano</ActionText></Action></FormCard><FlatList data={plans} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhum plano preventivo encontrado.</Empty>} renderItem={({ item }) => <Card><Title>{item.title || 'Plano preventivo'}</Title><Detail>{item.assetIdentifier || 'Patrimônio não informado'} · a cada {item.frequencyDays || '—'} dias</Detail><Detail>Próxima execução: {date(item.nextAt)}</Detail></Card>} /></>}
    {['chamados', 'ordens-list', 'preventivas-list'].includes(section) && <FloatingAction accessibilityLabel="Adicionar" onPress={() => setSection(section === 'chamados' ? 'novo' : section === 'ordens-list' ? 'ordens' : 'preventivas')}><MaterialCommunityIcons name="plus" size={30} color="#fff" /></FloatingAction>}
    {section === 'ordens-list' && <FlatList data={orders} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 100 }} ListEmptyComponent={<Empty>Nenhuma ordem encontrada.</Empty>} renderItem={({ item }) => <Card onPress={() => setSelectedWork({ ...item, kind: 'order' })}><Title>{item.identifier || item.subject || item.id}</Title><Detail>{item.assetDescription || 'Patrimônio não informado'} · {STATUS[item.status] || item.status || 'Aberta'}</Detail><Detail>Técnico: {item.technicianName || 'Não definido'}</Detail></Card>} />}
    {section === 'preventivas-list' && <FlatList data={plans} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 100 }} ListEmptyComponent={<Empty>Nenhum plano preventivo encontrado.</Empty>} renderItem={({ item }) => <Card><Title>{item.title || 'Plano preventivo'}</Title><Detail>{item.assetIdentifier || 'Patrimônio não informado'} · a cada {item.frequencyDays || '—'} dias</Detail><Detail>Próxima execução: {date(item.nextAt)}</Detail></Card>} />}
  </PortalBackground>;
}
