import { MaterialCommunityIcons } from '@expo/vector-icons';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, ScrollView, TextInput } from 'react-native';
import styled from 'styled-components/native';

import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';
import { runAdministrativeCommand } from '../../services/AdministrativeCommand';
import { firestore } from '../../services/firebaseConfig';

const Bar = styled.View`padding: 14px 18px 6px;`;
const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`;
const ChipText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.card};`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`;
const Row = styled.View`flex-direction: row; align-items: center;`;
const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`;
const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`;
const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px;`;
const FormCard = styled(PortalCard)`margin: 18px;`;
const Label = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 13px; font-weight: 800; margin-top: 12px;`;
const Input = styled(TextInput)`min-height: 44px; margin-top: 7px; padding: 0 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt};`;
const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary};`;
const ActionText = styled.Text`color: #fff; font-weight: 900;`;
const STATUS = { open: 'Aberto', triage: 'Em triagem', assigned: 'Atribuída', in_progress: 'Em execução', awaiting_material: 'Aguardando material', awaiting_supplier: 'Aguardando fornecedor', completed: 'Concluída', validated: 'Validada', closed: 'Encerrada' };
const useRows = name => { const [rows, setRows] = useState([]); useEffect(() => onSnapshot(query(collection(firestore, name), orderBy('createdAt', 'desc')), snap => setRows(snap.docs.map(row => ({ id: row.id, ...row.data() }))), () => setRows([])), [name]); return rows; };
const date = value => value?.toDate ? value.toDate().toLocaleDateString('pt-BR') : value ? new Date(value).toLocaleDateString('pt-BR') : 'Não informado';

export default function AdminManutencaoScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules(); const tickets = useRows('maintenanceTickets'); const orders = useRows('maintenanceWorkOrders'); const plans = useRows('maintenancePlans'); const assets = useRows('assets');
  const [section, setSection] = useState('resumo'); const [search, setSearch] = useState(''); const [form, setForm] = useState({ assetId: '', subject: '', description: '', priority: 'normal', departmentName: '' }); const [order, setOrder] = useState({ ticketId: '', technicianName: '', supplierName: '', contractId: '', diagnosis: '', estimatedCost: '' }); const [plan, setPlan] = useState({ assetId: '', title: '', description: '', frequencyDays: '30', nextAt: '', responsibleName: '', contractId: '' }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const run = async (action, payload, success) => { setBusy(true); setMessage(''); try { await runAdministrativeCommand('manutencao', action, payload); setMessage(success); } catch (error) { setMessage(error.message || 'Não foi possível concluir a operação.'); } finally { setBusy(false); } };
  const filteredTickets = useMemo(() => tickets.filter(item => `${item.identifier} ${item.subject} ${item.assetDescription} ${item.requesterName}`.toLowerCase().includes(search.toLowerCase())), [tickets, search]);
  const createTicket = () => { if (!form.subject.trim() || !form.description.trim()) return Alert.alert('Atenção', 'Informe o problema e a descrição.'); const asset = assets.find(item => item.id === form.assetId); run('createTicket', { ...form, assetIdentifier: asset?.tombNumber || asset?.identifier || '', assetDescription: asset?.description || '' }, 'Chamado aberto com sucesso.'); setForm({ assetId: '', subject: '', description: '', priority: 'normal', departmentName: '' }); };
  const createOrder = () => { if (!order.ticketId) return Alert.alert('Atenção', 'Selecione um chamado.'); run('createWorkOrder', order, 'Ordem de serviço criada.'); setOrder({ ticketId: '', technicianName: '', supplierName: '', contractId: '', diagnosis: '', estimatedCost: '' }); };
  const createPlan = () => { if (!plan.title.trim()) return Alert.alert('Atenção', 'Informe o título do plano.'); const asset = assets.find(item => item.id === plan.assetId); run('createPlan', { ...plan, assetIdentifier: asset?.tombNumber || asset?.identifier || '' }, 'Plano preventivo criado.'); setPlan({ assetId: '', title: '', description: '', frequencyDays: '30', nextAt: '', responsibleName: '', contractId: '' }); };
  const nextStatus = { open: 'triage', triage: 'assigned', assigned: 'in_progress', in_progress: 'completed', awaiting_material: 'in_progress', awaiting_supplier: 'in_progress', completed: 'validated', validated: 'closed' };
  if (!canUseAdminApp('manutencao')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  return <PortalBackground><PortalScreenHeader navigation={navigation} eyebrow="Área administrativa" title="Manutenção Patrimonial" subtitle="Centralize chamados, ordens de serviço e planos preventivos." /><Bar><Horizontal>{[['resumo', 'Visão geral'], ['chamados', 'Chamados'], ['ordens', 'Ordens de serviço'], ['preventivas', 'Preventivas']].map(([id, label]) => <Chip key={id} active={section === id} onPress={() => setSection(id)}><ChipText active={section === id}>{label}</ChipText></Chip>)}</Horizontal>{section === 'chamados' && <Search value={search} onChangeText={setSearch} placeholder="Buscar chamado, patrimônio ou solicitante" placeholderTextColor="#94a3b8" />}</Bar>{message ? <Detail style={{ marginHorizontal: 18 }}>{message}</Detail> : null}
    {section === 'resumo' && <ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 40 }}><FormCard><Title>Resumo da manutenção</Title><Detail>{tickets.length} chamado(s)</Detail><Detail>{orders.length} ordem(ns) de serviço</Detail><Detail>{plans.length} plano(s) preventivo(s)</Detail><Detail>{orders.filter(item => !['completed', 'validated', 'closed'].includes(item.status)).length} ordem(ns) em aberto</Detail></FormCard><FormCard><Title>Chamados recentes</Title>{tickets.slice(0, 6).map(item => <Detail key={item.id}>{item.identifier || item.id} · {item.subject || 'Sem assunto'} · {STATUS[item.status] || item.status || 'Aberto'}</Detail>)}{!tickets.length && <Detail>Nenhum chamado registrado.</Detail>}</FormCard></ScrollView>}
    {section === 'chamados' && <><Action onPress={() => setSection('novo')}><ActionText>Novo chamado</ActionText></Action><FlatList data={filteredTickets} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhum chamado encontrado.</Empty>} renderItem={({ item }) => <Card><Row><MaterialCommunityIcons name="tools" size={29} color="#d97706" /><Info><Title>{item.identifier || item.subject || item.id}</Title><Detail>{item.subject || 'Problema não informado'} · {STATUS[item.status] || item.status || 'Aberto'}</Detail><Detail>{item.assetIdentifier || 'Sem patrimônio vinculado'} · {date(item.createdAt)}</Detail></Info><Chip active={false} onPress={() => nextStatus[item.status] && run('transitionWorkOrder', { id: item.id, status: nextStatus[item.status] }, 'Status atualizado.')}><ChipText active={false}>Avançar</ChipText></Chip></Row></Card>} /></>}
    {section === 'novo' && <FormCard><Title>Abrir chamado</Title><Label>Patrimônio</Label><Input value={form.assetId} onChangeText={assetId => setForm({ ...form, assetId })} placeholder="ID do bem (opcional)" placeholderTextColor="#94a3b8" /><Label>Problema *</Label><Input value={form.subject} onChangeText={subject => setForm({ ...form, subject })} placeholder="Descreva o problema" placeholderTextColor="#94a3b8" /><Label>Descrição *</Label><Input multiline value={form.description} onChangeText={description => setForm({ ...form, description })} placeholder="Detalhe a necessidade de manutenção" placeholderTextColor="#94a3b8" /><Label>Setor</Label><Input value={form.departmentName} onChangeText={departmentName => setForm({ ...form, departmentName })} placeholder="Setor" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={createTicket}><ActionText>Abrir chamado</ActionText></Action></FormCard>}
    {section === 'ordens' && <><FormCard><Title>Criar ordem de serviço</Title><Label>Chamado (ID) *</Label><Input value={order.ticketId} onChangeText={ticketId => setOrder({ ...order, ticketId })} placeholder="ID do chamado" placeholderTextColor="#94a3b8" /><Label>Técnico</Label><Input value={order.technicianName} onChangeText={technicianName => setOrder({ ...order, technicianName })} placeholder="Técnico responsável" placeholderTextColor="#94a3b8" /><Label>Fornecedor</Label><Input value={order.supplierName} onChangeText={supplierName => setOrder({ ...order, supplierName })} placeholder="Empresa/fornecedor" placeholderTextColor="#94a3b8" /><Label>Diagnóstico</Label><Input multiline value={order.diagnosis} onChangeText={diagnosis => setOrder({ ...order, diagnosis })} placeholder="Diagnóstico" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={createOrder}><ActionText>Criar ordem</ActionText></Action></FormCard><FlatList data={orders} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhuma ordem encontrada.</Empty>} renderItem={({ item }) => <Card><Title>{item.identifier || item.subject || item.id}</Title><Detail>{item.assetDescription || 'Patrimônio não informado'} · {STATUS[item.status] || item.status || 'Aberta'}</Detail><Detail>Técnico: {item.technicianName || 'Não definido'}</Detail></Card>} /></>}
    {section === 'preventivas' && <><FormCard><Title>Novo plano preventivo</Title><Label>Patrimônio</Label><Input value={plan.assetId} onChangeText={assetId => setPlan({ ...plan, assetId })} placeholder="ID do bem" placeholderTextColor="#94a3b8" /><Label>Título *</Label><Input value={plan.title} onChangeText={title => setPlan({ ...plan, title })} placeholder="Ex.: Revisão elétrica" placeholderTextColor="#94a3b8" /><Label>Periodicidade em dias</Label><Input value={plan.frequencyDays} onChangeText={frequencyDays => setPlan({ ...plan, frequencyDays })} keyboardType="numeric" placeholder="30" placeholderTextColor="#94a3b8" /><Label>Próxima execução</Label><Input value={plan.nextAt} onChangeText={nextAt => setPlan({ ...plan, nextAt })} placeholder="AAAA-MM-DD" placeholderTextColor="#94a3b8" /><Label>Descrição</Label><Input multiline value={plan.description} onChangeText={description => setPlan({ ...plan, description })} placeholder="Checklist e orientações" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={createPlan}><ActionText>Criar plano</ActionText></Action></FormCard><FlatList data={plans} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhum plano preventivo encontrado.</Empty>} renderItem={({ item }) => <Card><Title>{item.title || 'Plano preventivo'}</Title><Detail>{item.assetIdentifier || 'Patrimônio não informado'} · a cada {item.frequencyDays || '—'} dias</Detail><Detail>Próxima execução: {date(item.nextAt)}</Detail></Card>} /></>}
  </PortalBackground>;
}
