import { MaterialCommunityIcons } from '@expo/vector-icons';
import { httpsCallable } from 'firebase/functions';
import { useCallback, useEffect, useState } from 'react';
import { Alert, FlatList, ScrollView, TextInput } from 'react-native';
import styled from 'styled-components/native';

import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';
import { functions } from '../../services/firebaseConfig';

const api = httpsCallable(functions, 'esic');
const Bar = styled.View`padding: 14px 18px 6px;`; const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`; const ChipText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.card};`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`; const Row = styled.View`flex-direction: row; align-items: center;`; const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`; const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`; const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px;`;
const DetailCard = styled(PortalCard)`margin: 18px;`; const Label = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; font-weight: 800; margin-top: 14px;`; const Value = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; line-height: 22px; margin-top: 4px;`; const Input = styled(TextInput)`min-height: 90px; margin-top: 10px; padding: 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt}; text-align-vertical: top;`; const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary};`; const ActionText = styled.Text`color: #fff; font-weight: 900;`;
const STATUSES = ['Todos', 'Recebido', 'Em análise', 'Respondido', 'Em recurso', 'Concluído']; const date = value => value ? new Date(value).toLocaleString('pt-BR') : 'Não informado';

export default function AdminEsicScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules(); const [items, setItems] = useState([]); const [status, setStatus] = useState('Todos'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState(null); const [action, setAction] = useState(''); const [text, setText] = useState(''); const [responsavel, setResponsavel] = useState(''); const [setor, setSetor] = useState('SIC'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setBusy(true); setError(''); try { const result = await api({ action: 'list', admin: true, status: status === 'Todos' ? '' : status, protocolo: search }); setItems(result.data?.items || []); } catch (failure) { setError(failure.message || 'Não foi possível carregar os pedidos e-SIC.'); } finally { setBusy(false); } }, [search, status]);
  useEffect(() => { if (canUseAdminApp('esic')) load(); }, [canUseAdminApp, load]);
  if (!canUseAdminApp('esic')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  const open = async id => { setBusy(true); try { const result = await api({ action: 'detail', id }); setSelected(result.data); setAction(''); setText(''); } catch (failure) { Alert.alert('Erro', failure.message || 'Não foi possível abrir o pedido.'); } finally { setBusy(false); } };
  const submitAction = async actionName => { if (!selected || !text.trim() && ['respond', 'note', 'decide', 'extend'].includes(actionName)) return Alert.alert('Atenção', 'Informe o texto da ação.'); setBusy(true); try { const payload = { action: actionName, id: selected.id, texto: text.trim(), responsavel: responsavel.trim(), setor: setor.trim() }; const result = await api(payload); setSelected(result.data?.id ? result.data : selected); setAction(''); setText(''); await load(); Alert.alert('Sucesso', 'Pedido atualizado.'); } catch (failure) { Alert.alert('Erro', failure.message || 'Não foi possível atualizar o pedido.'); } finally { setBusy(false); } };
  if (selected) return <PortalBackground><PortalScreenHeader navigation={{ goBack: () => setSelected(null) }} eyebrow="Área administrativa" title={selected.protocolo || 'Pedido e-SIC'} subtitle="Detalhes e providências do atendimento." /><DetailCard><Title>{selected.titulo || 'Pedido de informação'}</Title><Label>Descrição</Label><Value>{selected.descricao || 'Não informada.'}</Value><Label>Status</Label><Value>{selected.status || 'Não informado'}</Value><Label>Prazo</Label><Value>{date(selected.deadline)}</Value><Label>Responsável</Label><Value>{selected.responsavel || 'Aguardando distribuição'}</Value><Label>Setor</Label><Value>{selected.setor || 'SIC'}</Value><Horizontal><Chip active={false} onPress={() => setAction('assign')}><ChipText active={false}>Distribuir</ChipText></Chip><Chip active={false} onPress={() => setAction('respond')}><ChipText active={false}>Responder</ChipText></Chip><Chip active={false} onPress={() => setAction('extend')}><ChipText active={false}>Prorrogar</ChipText></Chip><Chip active={false} onPress={() => setAction('note')}><ChipText active={false}>Nota interna</ChipText></Chip></Horizontal>{action === 'assign' && <><Label>Responsável</Label><Search value={responsavel} onChangeText={setResponsavel} placeholder="Nome do responsável" placeholderTextColor="#94a3b8" /><Label>Setor</Label><Search value={setor} onChangeText={setSetor} placeholder="Setor" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={() => submitAction('assign')}><ActionText>Distribuir pedido</ActionText></Action></>}{['respond', 'extend', 'note'].includes(action) && <><Label>{action === 'respond' ? 'Resposta ao cidadão' : action === 'extend' ? 'Justificativa da prorrogação' : 'Nota para a equipe'}</Label><Input multiline value={text} onChangeText={setText} placeholder="Escreva o registro" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={() => submitAction(action)}><ActionText>Salvar ação</ActionText></Action></>}<Label>Histórico</Label>{(selected.historico || []).map((item, index) => <Value key={item.id || index}>{item.acao || 'Atualização'} · {date(item.data)}{item.texto ? `\n${item.texto}` : ''}</Value>)}{!selected.historico?.length && <Value>Nenhuma atualização registrada.</Value>}</DetailCard></PortalBackground>;
  return <PortalBackground><PortalScreenHeader navigation={navigation} eyebrow="Área administrativa" title="e-SIC" subtitle="Organize pedidos, prazos, respostas e recursos." /><Bar><Horizontal>{STATUSES.map(item => <Chip key={item} active={status === item} onPress={() => setStatus(item)}><ChipText active={status === item}>{item}</ChipText></Chip>)}</Horizontal><Search value={search} onChangeText={setSearch} placeholder="Buscar por protocolo" placeholderTextColor="#94a3b8" /></Bar>{error ? <Empty>{error}</Empty> : null}<FlatList data={items} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 36 }} ListEmptyComponent={!busy ? <Empty>Nenhum pedido encontrado.</Empty> : null} renderItem={({ item }) => <Card onPress={() => open(item.id)}><Row><MaterialCommunityIcons name="information-outline" size={29} color="#0f766e" /><Info><Title>{item.protocolo || item.id}</Title><Detail>{item.titulo || 'Pedido de informação'}</Detail><Detail>{item.status || 'Não informado'} · Prazo: {date(item.deadline)}</Detail><Detail>{item.responsavel || 'Aguardando distribuição'}</Detail></Info><MaterialCommunityIcons name="chevron-right" size={22} color="#94a3b8" /></Row></Card>} /></PortalBackground>;
}
