import { MaterialCommunityIcons } from '@expo/vector-icons';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, ScrollView, TextInput } from 'react-native';
import styled from 'styled-components/native';

import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';
import { runAdministrativeCommand } from '../../services/AdministrativeCommand';
import { firestore } from '../../services/firebaseConfig';

const Bar = styled.View`padding: 14px 18px 6px;`;
const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`;
const ChipText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.card};`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`;
const Row = styled.View`flex-direction: row; align-items: center;`;
const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`;
const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`;
const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px;`;
const FormCard = styled(PortalCard)`margin: 18px;`;
const Label = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 13px; font-weight: 800; margin-top: 12px;`;
const Input = styled(TextInput)`height: 44px; margin-top: 7px; padding: 0 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt};`;
const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary};`;
const ActionText = styled.Text`color: #fff; font-weight: 900;`;
const STATUS = { requested: 'Solicitado', awaiting_authorization: 'Aguardando autorização', authorized: 'Autorizado', separating: 'Em separação', delivered: 'Entregue', received: 'Recebido', cancelled: 'Cancelado' };
const MOVEMENTS = { entry: 'Entrada', exit: 'Saída', transfer: 'Transferência', return: 'Devolução', adjustment: 'Ajuste', loss: 'Perda' };
const date = value => value?.toDate ? value.toDate().toLocaleDateString('pt-BR') : value ? new Date(value).toLocaleDateString('pt-BR') : 'Não informado';
const useRows = name => { const [rows, setRows] = useState([]); useEffect(() => onSnapshot(query(collection(firestore, name), orderBy('createdAt', 'desc')), snap => setRows(snap.docs.map(row => ({ id: row.id, ...row.data() }))), () => setRows([])), [name]); return rows; };

export default function AdminAlmoxarifadoScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules(); const products = useRows('inventoryProducts'); const warehouses = useRows('inventoryWarehouses'); const movements = useRows('inventoryMovements'); const requests = useRows('materialRequests');
  const [section, setSection] = useState('resumo'); const [search, setSearch] = useState(''); const [form, setForm] = useState({ code: '', description: '', category: '', unit: 'UN', minimumStock: '0', maximumStock: '0' }); const [request, setRequest] = useState({ productId: '', warehouseId: '', quantity: '1', justification: '', departmentName: '' }); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const run = async (action, payload, success) => { setBusy(true); setMessage(''); try { await runAdministrativeCommand('almoxarifado', action, payload); setMessage(success); } catch (error) { setMessage(error.message || 'Não foi possível concluir a operação.'); } finally { setBusy(false); } };
  const filteredProducts = useMemo(() => products.filter(item => `${item.code} ${item.description} ${item.category}`.toLowerCase().includes(search.toLowerCase())), [products, search]);
  if (!canUseAdminApp('almoxarifado')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  const submitProduct = () => { if (!form.description.trim()) return Alert.alert('Atenção', 'Informe a descrição do produto.'); run('createProduct', form, 'Produto cadastrado com sucesso.'); setForm({ code: '', description: '', category: '', unit: 'UN', minimumStock: '0', maximumStock: '0' }); };
  const submitRequest = () => { const product = products.find(item => item.id === request.productId); if (!product || !request.warehouseId || !request.justification.trim()) return Alert.alert('Atenção', 'Informe produto, depósito e justificativa.'); run('createRequest', { warehouseId: request.warehouseId, departmentName: request.departmentName, justification: request.justification, items: [{ productId: product.id, productDescription: product.description, quantity: request.quantity }] }, 'Requisição criada com sucesso.'); setRequest({ productId: '', warehouseId: '', quantity: '1', justification: '', departmentName: '' }); };
  const advance = item => { const next = { requested: 'awaiting_authorization', awaiting_authorization: 'authorized', authorized: 'separating', separating: 'delivered', delivered: 'received' }[item.status]; if (next) run('transitionRequest', { id: item.id, status: next }, 'Requisição atualizada.'); };
  return <PortalBackground><PortalScreenHeader navigation={navigation} eyebrow="Área administrativa" title="Almoxarifado" subtitle="Controle materiais, depósitos, requisições e movimentações." /><Bar><Horizontal>{[['resumo', 'Visão geral'], ['produtos', 'Produtos'], ['depositos', 'Depósitos'], ['requisicoes', 'Requisições'], ['movimentacoes', 'Movimentações']].map(([id, label]) => <Chip key={id} active={section === id} onPress={() => setSection(id)}><ChipText active={section === id}>{label}</ChipText></Chip>)}</Horizontal>{(section === 'produtos' || section === 'movimentacoes') && <Search value={search} onChangeText={setSearch} placeholder="Buscar item" placeholderTextColor="#94a3b8" />}</Bar>
    {message ? <Detail style={{ marginHorizontal: 18 }}>{message}</Detail> : null}
    {section === 'resumo' && <ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 40 }}><FormCard><Title>Resumo do estoque</Title><Detail>{products.length} produto(s) cadastrado(s)</Detail><Detail>{warehouses.length} depósito(s)</Detail><Detail>{movements.length} movimentação(ões) registrada(s)</Detail><Detail>{requests.filter(item => !['received', 'cancelled'].includes(item.status)).length} requisição(ões) pendente(s)</Detail></FormCard><FormCard><Title>Estoque baixo</Title>{products.filter(item => Number(item.currentStock || 0) <= Number(item.minimumStock || 0)).slice(0, 8).map(item => <Detail key={item.id}>{item.description}: {item.currentStock || 0} {item.unit || ''}</Detail>)}{!products.some(item => Number(item.currentStock || 0) <= Number(item.minimumStock || 0)) && <Detail>Nenhum produto abaixo do mínimo.</Detail>}</FormCard></ScrollView>}
    {section === 'produtos' && <><Action disabled={busy} onPress={submitProduct}><ActionText>Novo produto</ActionText></Action><FormCard><Label>Código</Label><Input value={form.code} onChangeText={code => setForm({ ...form, code })} placeholder="Código" placeholderTextColor="#94a3b8" /><Label>Descrição *</Label><Input value={form.description} onChangeText={description => setForm({ ...form, description })} placeholder="Descrição" placeholderTextColor="#94a3b8" /><Label>Categoria</Label><Input value={form.category} onChangeText={category => setForm({ ...form, category })} placeholder="Categoria" placeholderTextColor="#94a3b8" /><Label>Unidade</Label><Input value={form.unit} onChangeText={unit => setForm({ ...form, unit })} placeholder="UN" placeholderTextColor="#94a3b8" /></FormCard><FlatList data={filteredProducts} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhum produto encontrado.</Empty>} renderItem={({ item }) => <Card><Row><MaterialCommunityIcons name="package-variant-closed" size={28} color="#0f766e" /><Info><Title>{item.code || 'Sem código'} · {item.description}</Title><Detail>{item.category || 'Sem categoria'} · Estoque: {item.currentStock || 0} {item.unit || ''}</Detail><Detail>Mínimo: {item.minimumStock || 0} · Máximo: {item.maximumStock || 0}</Detail></Info></Row></Card>} /></>}
    {section === 'depositos' && <FlatList data={warehouses} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhum depósito cadastrado.</Empty>} renderItem={({ item }) => <Card><Title>{item.code || 'Sem código'} · {item.name}</Title><Detail>{item.location || 'Localização não informada'}</Detail><Detail>Responsável: {item.responsibleName || 'Não informado'}</Detail></Card>} />}
    {section === 'requisicoes' && <><Action onPress={() => setSection('nova-requisicao')}><ActionText>Nova requisição</ActionText></Action><FlatList data={requests} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhuma requisição encontrada.</Empty>} renderItem={({ item }) => <Card><Row><MaterialCommunityIcons name="clipboard-list-outline" size={28} color="#0284C7" /><Info><Title>{item.identifier || item.id}</Title><Detail>{item.requesterName || 'Solicitante não informado'} · {item.departmentName || 'Setor não informado'}</Detail><Detail>{STATUS[item.status] || item.status || 'Não informado'} · {date(item.createdAt)}</Detail></Info><Chip active={false} onPress={() => advance(item)}><ChipText active={false}>Avançar</ChipText></Chip></Row></Card>} /></>}
    {section === 'nova-requisicao' && <FormCard><Title>Solicitar material</Title><Label>Produto (ID)</Label><Input value={request.productId} onChangeText={productId => setRequest({ ...request, productId })} placeholder="Cole o ID do produto" placeholderTextColor="#94a3b8" /><Label>Depósito (ID)</Label><Input value={request.warehouseId} onChangeText={warehouseId => setRequest({ ...request, warehouseId })} placeholder="Cole o ID do depósito" placeholderTextColor="#94a3b8" /><Label>Quantidade</Label><Input value={request.quantity} onChangeText={quantity => setRequest({ ...request, quantity })} keyboardType="numeric" placeholder="1" placeholderTextColor="#94a3b8" /><Label>Setor</Label><Input value={request.departmentName} onChangeText={departmentName => setRequest({ ...request, departmentName })} placeholder="Setor solicitante" placeholderTextColor="#94a3b8" /><Label>Justificativa *</Label><Input value={request.justification} onChangeText={justification => setRequest({ ...request, justification })} placeholder="Motivo da solicitação" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={submitRequest}><ActionText>Enviar requisição</ActionText></Action></FormCard>}
    {section === 'movimentacoes' && <FlatList data={movements.filter(item => `${item.productDescription} ${item.createdByName}`.toLowerCase().includes(search.toLowerCase()))} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhuma movimentação encontrada.</Empty>} renderItem={({ item }) => <Card><Title>{MOVEMENTS[item.type] || item.type || 'Movimentação'}</Title><Detail>{item.productDescription || 'Produto não informado'} · Quantidade: {item.quantity || 0}</Detail><Detail>{date(item.createdAt)} · {item.createdByName || 'Responsável não informado'}</Detail></Card>} />}
  </PortalBackground>;
}
