import { MaterialCommunityIcons } from '@expo/vector-icons';
import { collection, doc, onSnapshot, serverTimestamp, updateDoc } from 'firebase/firestore';
import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, ScrollView, TextInput } from 'react-native';
import styled from 'styled-components/native';
import { firestore } from '../../services/firebaseConfig';
import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';

const STATUSES = ['Todas', 'Recebida', 'Em Acolhimento', 'Encaminhada', 'Concluída', 'Não Classificado'];
const normalize = value => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const dateOf = item => item.dataManifestacao?.toDate ? item.dataManifestacao.toDate() : new Date(item.dataManifestacao || item.createdAt || 0);
const dateLabel = item => { const value = dateOf(item); return Number.isNaN(value.getTime()) ? 'Data não informada' : value.toLocaleString('pt-BR'); };
const messagesOf = value => Array.isArray(value) ? value : Object.entries(value || {}).map(([id, message]) => ({ id, ...message }));

const FilterBar = styled.View`padding: 14px 18px 6px;`;
const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`;
const ChipText = styled.Text`font-size: 12px; font-weight: 800; color: ${({ active, theme }) => active ? '#fff' : theme.portal.text};`;
const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; background-color: ${({ theme }) => theme.portal.card}; color: ${({ theme }) => theme.portal.text}; font-size: 12px;`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`;
const Row = styled.View`flex-direction: row; align-items: center;`;
const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`;
const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`;
const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px; line-height: 22px;`;
const DetailCard = styled(PortalCard)`margin: 18px;`;
const Label = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; font-weight: 800; margin-top: 14px;`;
const Value = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; line-height: 22px; margin-top: 4px;`;
const Tabs = styled.View`flex-direction: row; flex-wrap: wrap; padding: 14px 18px 0;`;
const Tab = styled.TouchableOpacity`padding: 10px 12px; margin: 0 7px 8px 0; border-radius: 10px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card};`;
const TabText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 900;`;
const StatusButton = styled.TouchableOpacity`padding: 10px 12px; border-radius: 10px; margin: 8px 7px 0 0; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.pageAlt};`;
const StatusText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const MessageInput = styled(TextInput)`min-height: 90px; margin-top: 10px; padding: 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt}; text-align-vertical: top;`;
const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary}; opacity: ${({ disabled }) => disabled ? .55 : 1};`;
const ActionText = styled.Text`color: #fff; font-weight: 900;`;
const MessageRow = styled.View`padding: 12px 0; border-bottom-width: 1px; border-bottom-color: ${({ theme }) => theme.portal.border};`;

export default function AdminOuvidoriaScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules();
  const [items, setItems] = useState([]); const [status, setStatus] = useState('Todas'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState(null); const [tab, setTab] = useState('dados'); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!canUseAdminApp('ouvidoria')) return undefined; return onSnapshot(collection(firestore, 'ouvidoria'), snapshot => setItems(snapshot.docs.map(row => ({ id: row.id, ...row.data() })))); }, [canUseAdminApp]);
  const visible = useMemo(() => items.filter(item => { const text = normalize(`${item.dadosManifestacao?.assunto || ''} ${item.dadosManifestacao?.descricao || ''} ${item.dadosManifestacao?.tipo || ''} ${item.dadosUsuario?.name || ''} ${item.id}`); return (status === 'Todas' || normalize(item.status || 'Não Classificado') === normalize(status)) && (!search.trim() || text.includes(normalize(search))); }).sort((a, b) => dateOf(b) - dateOf(a)), [items, search, status]);
  if (!canUseAdminApp('ouvidoria')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /> </PortalBackground>;
  const update = async updates => { if (!selected) return; setSaving(true); try { await updateDoc(doc(firestore, 'ouvidoria', selected.id), { ...updates, ultimaAtualizacao: serverTimestamp() }); setSelected(current => ({ ...current, ...updates })); setItems(current => current.map(item => item.id === selected.id ? { ...item, ...updates } : item)); } catch (error) { Alert.alert('Erro', error.message || 'Não foi possível atualizar a manifestação.'); } finally { setSaving(false); } };
  if (selected) return <PortalBackground><PortalScreenHeader navigation={{ goBack: () => setSelected(null) }} eyebrow="Área administrativa" title="Ouvidoria" subtitle={selected.protocolo || selected.id} /><Tabs>{[['dados', 'Dados'], ['situacao', 'Situação'], ['agendamento', 'Agendamento'], ['arquivos', 'Arquivos'], ['chat', 'Chat']].map(([id, label]) => <Tab key={id} active={tab === id} onPress={() => setTab(id)}><TabText active={tab === id}>{label}</TabText></Tab>)}</Tabs><DetailCard>{tab === 'dados' && <><Label>Solicitante</Label><Value>{selected.dadosUsuario?.name || 'Não informado'}</Value><Label>Tipo de manifestação</Label><Value>{selected.dadosManifestacao?.tipo || selected.dadosManifestacao?.categoria || 'Não informado'}</Value><Label>Assunto</Label><Value>{selected.dadosManifestacao?.assunto || 'Não informado'}</Value><Label>Descrição</Label><Value>{selected.dadosManifestacao?.descricao || 'Não informado'}</Value></>}{tab === 'situacao' && <><Label>Status atual</Label><Value>{selected.status || 'Não Classificado'}</Value>{STATUSES.slice(1, -1).map(value => <StatusButton key={value} active={selected.status === value} disabled={saving} onPress={() => update({ status: value })}><StatusText active={selected.status === value}>{value}</StatusText></StatusButton>)}</>}{tab === 'agendamento' && <><Label>Data</Label><Value>{selected.appointmentDate || 'Não agendado'}</Value><Label>Horário</Label><Value>{selected.appointmentTime || 'Não informado'}</Value></>}{tab === 'arquivos' && <><Label>Arquivos anexados</Label><Value>{selected.anexos ? 'Arquivos disponíveis no atendimento.' : 'Nenhum arquivo anexado.'}</Value></>}{tab === 'chat' && <>{messagesOf(selected.messages).map((item, index) => <MessageRow key={item.id || index}><Value>{item.text || item.message || ''}</Value><Label>{item.sender || 'Atendimento'}</Label></MessageRow>)}{!messagesOf(selected.messages).length && <Value>Nenhuma mensagem registrada.</Value>}<MessageInput multiline value={message} onChangeText={setMessage} placeholder="Digite uma mensagem para o cidadão..." placeholderTextColor="#94a3b8" /><Action disabled={saving || !message.trim()} onPress={() => { const id = `admin-${Date.now()}`; update({ [`messages.${id}`]: { text: message.trim(), sender: 'admin', timestamp: new Date().toISOString(), readByAdmin: true, readByUser: false } }); setMessage(''); }}><ActionText>{saving ? 'Enviando...' : 'Enviar mensagem'}</ActionText></Action></>}</DetailCard></PortalBackground>;
  return <PortalBackground><PortalScreenHeader navigation={navigation} eyebrow="Área administrativa" title="Ouvidoria" subtitle="Gerencie manifestações, encaminhamentos e atendimentos." /><FilterBar><Horizontal>{STATUSES.map(value => <Chip key={value} active={status === value} onPress={() => setStatus(value)}><ChipText active={status === value}>{value}</ChipText></Chip>)}</Horizontal><Search value={search} onChangeText={setSearch} placeholder="Buscar por cidadão, assunto ou protocolo" placeholderTextColor="#94a3b8" /></FilterBar><FlatList data={visible} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 36 }} ListEmptyComponent={<Empty>Nenhuma manifestação encontrada para este filtro.</Empty>} renderItem={({ item }) => <Card onPress={() => { setSelected(item); setTab('dados'); }}><Row><MaterialCommunityIcons name="bullhorn-outline" size={29} color="#0f766e" /><Info><Title>{item.dadosManifestacao?.assunto || 'Manifestação de Ouvidoria'}</Title><Detail>Solicitante: {item.dadosUsuario?.name || 'Não informado'}</Detail><Detail>{item.dadosManifestacao?.tipo || 'Manifestação'} · {item.status || 'Não Classificado'}</Detail><Detail>{dateLabel(item)}</Detail></Info><MaterialCommunityIcons name="chevron-right" size={22} color="#94a3b8" /></Row></Card>} /></PortalBackground>;
}
