import { MaterialCommunityIcons } from '@expo/vector-icons';
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore';
import { Fragment, useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, ScrollView, TextInput } from 'react-native';
import styled from 'styled-components/native';

import { PortalBackground, PortalCard, PortalScreenHeader } from '../components/PortalScaffold';
import { useMobileModules } from '../context/MobileModulesContext';
import { runAdministrativeCommand } from '../../services/AdministrativeCommand';
import { firestore } from '../../services/firebaseConfig';

const Bar = styled.View`padding: 14px 18px 6px;`;
const Horizontal = styled(ScrollView).attrs({ horizontal: true, showsHorizontalScrollIndicator: false })`margin-bottom: 8px;`;
const Chip = styled.TouchableOpacity`padding: 10px 13px; margin-right: 8px; border-radius: 12px; background-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.card}; border-width: 1px; border-color: ${({ active, theme }) => active ? theme.portal.primary : theme.portal.border};`;
const ChipText = styled.Text`color: ${({ active, theme }) => active ? '#fff' : theme.portal.text}; font-size: 12px; font-weight: 800;`;
const Search = styled(TextInput)`height: 44px; padding: 0 12px; border-radius: 11px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.card};`;
const Card = styled.TouchableOpacity`margin: 6px 18px; padding: 16px; border-radius: 14px; background-color: ${({ theme }) => theme.portal.card}; border-width: 1px; border-color: ${({ theme }) => theme.portal.border};`;
const Row = styled.View`flex-direction: row; align-items: center;`;
const Info = styled.View`flex: 1; margin-left: 12px;`;
const Title = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 15px; font-weight: 900;`;
const Detail = styled.Text`color: ${({ theme }) => theme.portal.muted}; font-size: 12px; margin-top: 4px;`;
const Empty = styled.Text`color: ${({ theme }) => theme.portal.muted}; text-align: center; margin: 36px 24px;`;
const FormCard = styled(PortalCard)`margin: 18px;`;
const Label = styled.Text`color: ${({ theme }) => theme.portal.text}; font-size: 13px; font-weight: 800; margin-top: 12px;`;
const Input = styled(TextInput)`height: 44px; margin-top: 7px; padding: 0 12px; border-radius: 10px; border-width: 1px; border-color: ${({ theme }) => theme.portal.border}; color: ${({ theme }) => theme.portal.text}; background-color: ${({ theme }) => theme.portal.pageAlt};`;
const Action = styled.TouchableOpacity`margin-top: 12px; padding: 13px; border-radius: 11px; align-items: center; background-color: ${({ theme }) => theme.portal.primary};`;
const ActionText = styled.Text`color: #fff; font-weight: 900;`;
const STATUS = { active: 'Em uso', maintenance: 'Em manutenção', loaned: 'Emprestado', written_off: 'Baixado' };
const CONSERVATION = { good: 'Bom', regular: 'Regular', poor: 'Ruim' };
const date = value => value?.toDate ? value.toDate().toLocaleDateString('pt-BR') : value ? new Date(value).toLocaleDateString('pt-BR') : 'Não informado';
const useRows = name => { const [rows, setRows] = useState([]); useEffect(() => onSnapshot(query(collection(firestore, name), orderBy('createdAt', 'desc')), snap => setRows(snap.docs.map(row => ({ id: row.id, ...row.data() }))), () => setRows([])), [name]); return rows; };

export default function AdminPatrimonioScreen({ navigation }) {
  const { canUseAdminApp } = useMobileModules(); const assets = useRows('assets'); const movements = useRows('assetMovements'); const inventories = useRows('assetInventories');
  const [section, setSection] = useState('resumo'); const [search, setSearch] = useState(''); const [form, setForm] = useState({ tombNumber: '', description: '', category: '', departmentName: '', location: '', responsibleName: '', conservationState: 'good', acquisitionValue: '' }); const [move, setMove] = useState({ assetId: '', type: 'transfer', departmentName: '', location: '', responsibleName: '', reason: '' }); const [inventoryName, setInventoryName] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const run = async (action, payload, success) => { setBusy(true); setMessage(''); try { await runAdministrativeCommand('patrimonio', action, payload); setMessage(success); } catch (error) { setMessage(error.message || 'Não foi possível concluir a operação.'); } finally { setBusy(false); } };
  const filtered = useMemo(() => assets.filter(item => `${item.tombNumber} ${item.description} ${item.category} ${item.departmentName}`.toLowerCase().includes(search.toLowerCase())), [assets, search]);
  if (!canUseAdminApp('patrimonio')) return <PortalBackground><PortalScreenHeader navigation={navigation} title="Acesso indisponível" /></PortalBackground>;
  const createAsset = () => { if (!form.description.trim()) return Alert.alert('Atenção', 'Informe a descrição do bem.'); run('createAsset', form, 'Bem patrimonial cadastrado.'); setForm({ tombNumber: '', description: '', category: '', departmentName: '', location: '', responsibleName: '', conservationState: 'good', acquisitionValue: '' }); };
  const moveAsset = () => { if (!move.assetId || !move.reason.trim()) return Alert.alert('Atenção', 'Informe o bem e o motivo da movimentação.'); run('moveAsset', move, 'Movimentação registrada.'); setMove({ assetId: '', type: 'transfer', departmentName: '', location: '', responsibleName: '', reason: '' }); };
  return <PortalBackground><PortalScreenHeader navigation={navigation} eyebrow="Área administrativa" title="Patrimônio" subtitle="Controle bens, localização, responsabilidade e inventários." /><Bar><Horizontal>{[['resumo', 'Visão geral'], ['bens', 'Bens'], ['novo', 'Novo bem'], ['movimentos', 'Movimentações'], ['inventarios', 'Inventários']].map(([id, label]) => <Chip key={id} active={section === id} onPress={() => setSection(id)}><ChipText active={section === id}>{label}</ChipText></Chip>)}</Horizontal>{section === 'bens' && <Search value={search} onChangeText={setSearch} placeholder="Buscar tombamento, bem ou setor" placeholderTextColor="#94a3b8" />}</Bar>{message ? <Detail style={{ marginHorizontal: 18 }}>{message}</Detail> : null}
    {section === 'resumo' && <ScrollView contentContainerStyle={{ padding: 18, paddingBottom: 40 }}><FormCard><Title>Resumo patrimonial</Title><Detail>{assets.length} bem(ns) cadastrado(s)</Detail><Detail>{assets.filter(item => item.status === 'maintenance').length} em manutenção</Detail><Detail>{inventories.filter(item => item.status === 'open').length} inventário(s) aberto(s)</Detail><Detail>{movements.length} movimentação(ões) registradas</Detail></FormCard><FormCard><Title>Por situação</Title>{Object.entries(STATUS).map(([key, label]) => <Detail key={key}>{label}: {assets.filter(item => item.status === key).length}</Detail>)}</FormCard></ScrollView>}
    {section === 'bens' && <FlatList data={filtered} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhum bem encontrado.</Empty>} renderItem={({ item }) => <Card><Row><MaterialCommunityIcons name="archive-outline" size={29} color="#7c3aed" /><Info><Title>{item.tombNumber || 'Sem tombamento'} · {item.description}</Title><Detail>{item.category || 'Sem categoria'} · {item.departmentName || 'Setor não informado'}</Detail><Detail>{STATUS[item.status] || item.status || 'Não informado'} · Conservação: {CONSERVATION[item.conservationState] || 'Não informado'}</Detail><Detail>Responsável: {item.responsibleName || 'Não informado'}</Detail></Info></Row></Card>} />}
    {section === 'novo' && <FormCard><Title>Novo bem patrimonial</Title>{[['tombNumber', 'Número de tombamento'], ['description', 'Descrição *'], ['category', 'Categoria'], ['departmentName', 'Setor'], ['location', 'Localização'], ['responsibleName', 'Responsável'], ['acquisitionValue', 'Valor de aquisição']].map(([key, label]) => <Fragment key={key}><Label>{label}</Label><Input value={form[key]} onChangeText={value => setForm({ ...form, [key]: value })} placeholder={label} placeholderTextColor="#94a3b8" /></Fragment>)}<Label>Conservação</Label><Horizontal>{Object.entries(CONSERVATION).map(([key, label]) => <Chip key={key} active={form.conservationState === key} onPress={() => setForm({ ...form, conservationState: key })}><ChipText active={form.conservationState === key}>{label}</ChipText></Chip>)}</Horizontal><Action disabled={busy} onPress={createAsset}><ActionText>Cadastrar bem</ActionText></Action></FormCard>}
    {section === 'movimentos' && <><FormCard><Title>Movimentar bem</Title><Label>ID do bem</Label><Input value={move.assetId} onChangeText={assetId => setMove({ ...move, assetId })} placeholder="Cole o ID do bem" placeholderTextColor="#94a3b8" /><Label>Tipo</Label><Horizontal>{[['transfer', 'Transferência'], ['loan', 'Empréstimo'], ['maintenance', 'Manutenção'], ['return', 'Retorno'], ['writeoff', 'Baixa']].map(([key, label]) => <Chip key={key} active={move.type === key} onPress={() => setMove({ ...move, type: key })}><ChipText active={move.type === key}>{label}</ChipText></Chip>)}</Horizontal><Label>Setor/localização de destino</Label><Input value={move.departmentName} onChangeText={departmentName => setMove({ ...move, departmentName })} placeholder="Destino" placeholderTextColor="#94a3b8" /><Label>Responsável</Label><Input value={move.responsibleName} onChangeText={responsibleName => setMove({ ...move, responsibleName })} placeholder="Responsável" placeholderTextColor="#94a3b8" /><Label>Motivo *</Label><Input value={move.reason} onChangeText={reason => setMove({ ...move, reason })} placeholder="Motivo da movimentação" placeholderTextColor="#94a3b8" /><Action disabled={busy} onPress={moveAsset}><ActionText>Registrar movimentação</ActionText></Action></FormCard><FlatList data={movements} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} renderItem={({ item }) => <Card><Title>{item.assetIdentifier || item.assetId}</Title><Detail>{item.type} · {item.toDepartmentName || item.departmentName || 'Destino não informado'}</Detail><Detail>{date(item.createdAt)} · {item.createdByName || 'Responsável não informado'}</Detail></Card>} /></>}
    {section === 'inventarios' && <><FormCard><Title>Abrir inventário</Title><Input value={inventoryName} onChangeText={setInventoryName} placeholder="Ex.: Inventário anual 2026" placeholderTextColor="#94a3b8" /><Action disabled={busy || !inventoryName.trim()} onPress={() => { run('createInventory', { name: inventoryName.trim() }, 'Inventário aberto.'); setInventoryName(''); }}><ActionText>Abrir inventário</ActionText></Action></FormCard><FlatList data={inventories} keyExtractor={item => item.id} contentContainerStyle={{ paddingBottom: 30 }} ListEmptyComponent={<Empty>Nenhum inventário cadastrado.</Empty>} renderItem={({ item }) => <Card><Title>{item.identifier || item.name}</Title><Detail>{item.name || 'Inventário patrimonial'} · {item.status === 'open' ? 'Aberto' : item.status || 'Concluído'}</Detail><Detail>Início: {date(item.startedAt || item.createdAt)}</Detail></Card>} /></>}
  </PortalBackground>;
}
